-- HD2-Addon: mods/alomare/flexible_stratagems
-- Flexible Stratagems by Alomare (formerly Stratagems Unleashed).
--
-- Lets the Hellpod loadout take the same stratagem more than once, vehicles included: up to 2, 3 or 4 copies of each,
-- set by a Mod Options Menu slider (escape menu > MODS; without it: 2).
-- Two rules are lifted in the stratagem list, on this game only (the loadout then goes out through the game's own
-- sync, so teammates need nothing):
--   * a stratagem already in the loadout is kept selectable: the list's refresh marks the loadout's stratagems as
--     equipped, and a press on an equipped item is refused; the mod marks back those with fewer copies than the limit
--     through the game's own marker, so picking one again runs the game's normal equip (slot, sync, save). After such
--     a pick the list's selection is cleared the game's way, since a press on the selected item plays no pick sound;
--   * one mech, one FRV and one tank: the equip handler moves a second one of a kind into the slot holding the first.
--     Its kind bits (stratagem info flags: 0x100000 mech, 0x200000 FRV, 0x400000 tank) are cleared while the list is
--     open and put back when it closes (or the screen closes, or on any error).
-- More, around the list:
--   * ready with empty slots: the ready handler refuses while fewer slots are filled than min(owned, 4), flashing the
--     empty ones (slots marked disabled, as by a mission modifier, don't count). The game's update runs before the
--     mod's, so the mod sees the flash start and toggles the ready the handler's way;
--   * after a replacement in a full loadout (slot 1 to 3), the equip handler closes the list; the mod focuses the
--     next slot and opens the list again, as the handler does while slots are still empty, then focuses the
--     stratagem just picked and puts the list's scroll back where it was;
--   * Clear Stratagems (a Mod Bindings Menu key): empties the four slots through the slot widgets, then writes and
--     saves the loadout the way a pick does.
-- Game updates: every address and structure offset the mod uses is read from the game's own code, found by code
-- signatures (at this build's addresses first, else by a search of game.dll spread over a few frames). Anything not
-- found, found twice or inconsistent turns the mod off, and the loadout works as normal. The verdict is the first line of
-- %LOCALAPPDATA%\CowboyBingus\Helldivers2\Logs\FlexibleStratagems_STATUS.log.
if rawget(_G, 'FlexibleStratagems') then return end

local ffi = require('ffi')
local bit = require('bit')

local M = {version = '4', frames = 0, errors = 0}
rawset(_G, 'FlexibleStratagems', M)

local loader = rawget(_G, 'CowboyBingusModLoader')

---------------------------------------------------------------------------------------
-- The game's code (research notes: NOTES.md beside this script)

-- BEGIN SIGNATURES (generated by research/signatures.py; game.dll build 25480438 addresses)
local SIGS = {
    {name = 'screen', rva = 0x1082ef0, text = '48 8B 05 ?? ?? ?? ?? 48 8B 88 ?? ?? ?? ?? 83 B9 ?? ?? ?? ?? FF 0F 95 C0 C3',
     fields = {stack = {'rip', {3}, {7}}, slot = {'u32', {10}}, local_index = {'u32', {16}}}},
    {name = 'category', rva = 0x146e0bc, text = '48 81 C1 ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 9F ?? ?? ?? ??',
     fields = {category = {'u32', {14}}}},
    {name = 'refresh_call', rva = 0x146e677, text = '8B 87 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? 48 69 D0 ?? ?? ?? ?? 48 83 C2 ?? 48 03 D7 E8 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {local_index = {'u32', {2}}, list = {'u32', {9}}, block_stride = {'u32', {16}}, block_base = {'u8', {23}}, refresh = {'call', {28}, {32}}}},
    {name = 'refresh_a', rva = 0x18d194f, text = '41 39 8C 24 ?? ?? ?? ?? 76 ?? 0F 1F 80 00 00 00 00 8B C1 FF C1 42 C6 84 20 ?? ?? ?? ?? 01 41 3B 8C 24 ?? ?? ?? ?? 72 ?? 45 39 BD ?? ?? ?? ?? 0F 86 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 8D 3D ?? ?? ?? ?? 0F 1F 40 00 66 66 0F 1F 84 00 00 00 00 00 4B 8D 0C 7F 48 03 C9 41 8B 84 CD ?? ?? ?? ?? 85 C0 75 ?? 48 8B C3 EB ?? 48 8B 04 C7 44 8B 58 04 45 85 DB 74 ??',
     fields = {list_count = {'u32', {4, 34}}, selectable = {'u32', {25}}, block_count = {'u32', {43}}, strat_table = {'rip', {63}, {67}}, block_entries = {'u32', {92}}}},
    {name = 'refresh_b', rva = 0x18d19c5, text = '4C 8B 0D ?? ?? ?? ?? 41 8B 91 ?? ?? ?? ?? 45 8B 91 ?? ?? ?? ?? 41 3B D2 73 ?? 4D 8D 81 ?? ?? ?? ?? 4D 8D 04 90 66 0F 1F 44 00 00 41 8B 00 48 8D 0C 40 49 8D 81 ?? ?? ?? ?? 44 39 5C C8 08 48 8D 04 C8 74 ?? FF C2 49 83 C0 04 41 3B D2 72 ?? EB ?? 48 85 C0 74 ?? 8B 50 04 45 33 C0 49 8B CC E8 ?? ?? ?? ??',
     fields = {offers = {'rip', {3}, {7}}, first = {'u32', {10}}, last = {'u32', {17}}, indices = {'u32', {29}}, entries = {'u32', {53}}, mark = {'call', {96}, {100}}}},
    {name = 'offers_count', rva = 0x146e1cf, text = '4C 8B 1D ?? ?? ?? ?? 85 D2 74 ?? 45 8B 83 ?? ?? ?? ?? 8B CE 45 85 C0 74 ?? 49 8D 83 ?? ?? ?? ??',
     fields = {offers = {'rip', {3}, {7}}, offers_count = {'u32', {14}}, entries = {'u32', {28}}}},
    {name = 'marker', rva = 0x18d1440, text = '48 89 74 24 10 57 48 83 EC 20 8B B9 14 1F 09 00 45 33 C9 45 33 DB 41 0F B6 F0 4C 8B D1 85 FF 0F 84 ?? ?? ?? ?? 48 89 5C 24 30 48 8D 99 18 23 09 00 44 8B 03 33 C0 45 85 C0 74 ?? 0F 1F 44 00 00 42 39 94 89 ?? ?? ?? ??',
     fields = {ids = {'u32', {68}}}},
    {name = 'select', rva = 0x18d10d0, text = '48 89 4C 24 08 56 41 55 41 56 48 83 EC 30 33 F6 48 89 5C 24 58 45 32 ED 4C 89 64 24 28 8B DA 4C 8B F1 44 8B E6 89 91 ?? ?? ?? ??',
     fields = {selected = {'u32', {39}}}},
    {name = 'kind_frv', rva = 0x146e2e0, text = '49 8B 0A 39 41 04 74 ?? 41 FF C0 49 83 C2 08 41 81 F8 ?? ?? ?? ?? 72 ?? 44 8B C6 48 8B C3 4C 8B DE EB ?? 44 8B C1 45 8B D8 4B 8B 04 DE F7 80 ?? ?? ?? ?? 00 00 20 00',
     fields = {types = {'u32', {18}}, flags = {'u32', {47}}}},
    {name = 'kind_mech', rva = 0x146e404, text = '45 85 C0 75 ?? 48 8B C3 EB ?? 41 8B C0 49 8B 04 C6 F7 80 ?? ?? ?? ?? 00 00 10 00',
     fields = {flags = {'u32', {19}}}},
    {name = 'kind_tank', rva = 0x146e4f5, text = '48 8B C3 45 85 C0 74 ?? 4B 8B 04 DE F7 80 ?? ?? ?? ?? 00 00 40 00',
     fields = {flags = {'u32', {14}}}},
    {name = 'ready_call', rva = 0x146d9fb, optional = true, text = '0F B6 83 ?? ?? ?? ?? 33 FF 84 C0 75 ?? 48 8D 8B ?? ?? ?? ?? 49 8B D7 E8 ?? ?? ?? ??',
     fields = {list_open = {'u32', {3}}, panels = {'u32', {16}}, ready_handler = {'call', {24}, {28}}}},
    {name = 'ready_slots', rva = 0x189c3b8, optional = true, text = '48 81 C7 ?? ?? ?? ?? 0F 29 BC 24 A0 00 00 00 0F 57 F6 F3 0F 10 3D ?? ?? ?? ?? 44 0F 29 84 24 90 00 00 00 F3 44 0F 10 05 ?? ?? ?? ?? 44 0F 29 8C 24 80 00 00 00 F3 44 0F 10 0D ?? ?? ?? ?? 85 F6 0F 84 ?? ?? ?? ?? 83 7F 04 00 75 ?? 80 7F ?? 00 75 ?? 0F B6 07 C0 E8 02 A8 01 75 ?? 0F 57 C0 F3 0F 11 74 24 40 66 0F 7F 44 24 70 48 8D 8F 10 F5 FF FF 41 0F 28 C0 C7 44 24 68 83 82 82 3E 8B 44 24 68 48 8D 54 24 50 89 44 24 58 41 B1 01 48 8D 44 24 70 41 0F 14 C1 48 89 44 24 38 0F 28 D7 F3 0F 11 74 24 30 C6 44 24 28 01 C7 44 24 20 02 00 00 00 F2 0F 11 44 24 50 E8 ?? ?? ?? ?? C6 47 ?? 01 FF CE FF C3 48 81 C7 ?? ?? ?? ?? 83 FB 04 0F 82 ?? ?? ?? ?? BA 01 05 0F F5 E8 ?? ?? ?? ??',
     fields = {slot_flags = {'u32', {3}}, flash = {'u8', {78, 191}}, slot_stride = {'u32', {200}}, ui_sound = {'call', {219}, {223}}}},
    {name = 'ready_toggle', rva = 0x189c4d0, optional = true, text = '4C 8B 05 ?? ?? ?? ?? 8B 87 ?? ?? ?? ?? 45 8B 90 ?? ?? ?? ?? 45 85 D2 74 ?? 4D 8D 88 ?? ?? ?? ?? 49 81 C0 ?? ?? ?? ?? 49 8B 08 39 41 08 74 ?? 83 FB FF 74 ?? 41 8B 11 8B CA C1 E9 03 80 E1 01 75 ?? C1 EA 0B 80 E2 01 74 ?? FF C3 49 83 C0 08 49 83 C1 20 41 3B DA 72 ?? B3 01 80 BF ?? ?? ?? ?? 00 0F 84 ?? ?? ?? ?? F3 0F 10 87 ?? ?? ?? ?? 0F 2E 05 ?? ?? ?? ?? 7A ?? 75 ?? 32 C0 EB ?? 32 DB EB ?? 8B 97 FC ED 01 00 0F 57 DB 41 B8 63 19 1D 5D F3 0F 11 5C 24 20 E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? C7 87 ?? ?? ?? ?? ?? ?? ?? ?? 83 BA ?? ?? ?? ?? 01 72 ?? 48 8B 8A ?? ?? ?? ?? F6 41 14 01 74 ?? 83 A2 ?? ?? ?? ?? F7 BA 01 05 0F F5 E8 ?? ?? ?? ?? 48 8B B4 24 F8 00 00 00 B8 04 00 00 00 48 81 C4 D8 00 00 00 5F 5B C3 8B D0 E8 ?? ?? ?? ?? 8B 97 FC ED 01 00 84 C0 75 ?? 0F 57 DB 41 B8 A4 50 E1 97 F3 0F 11 5C 24 20 E8 ?? ?? ?? ?? C7 87 ?? ?? ?? ?? ?? ?? ?? ?? 84 DB 74 ?? BA ?? ?? ?? ?? EB ?? BA ?? ?? ?? ??',
     fields = {player_count = {'u32', {16}}, panel_entity = {'u32', {9}}, panel_local = {'u32', {92}}, ready_timer = {'u32', {107, 165, 274}}, players = {'rip', {3, 159}, {7, 163}}, player_active = {'u32', {175}}, player_entries = {'u32', {35, 185}}, player_flags = {'u32', {28, 197}}, ui_sound = {'call', {208}, {212}}, timer_idle = {'u32', {169}}, ready_time = {'u32', {278}}, sound_ready_last = {'u32', {287}}, sound_ready = {'u32', {294}}}},
    {name = 'equip_tail', rva = 0x146e5f6, optional = true, text = '48 8D 8F ?? ?? ?? ?? 48 C7 C2 FF FF FF FF E8 ?? ?? ?? ?? 83 BF ?? ?? ?? ?? 01 74 ?? 48 8B 2D ?? ?? ?? ?? 4C 8D 9F ?? ?? ?? ?? 41 0F B6 43 FC C0 E8 02 A8 01 75 ?? 41 8B 1B 8D 43 FF 3D 94 00 00 00 0F 87 ?? ?? ?? ?? 8B D3 48 8B CD E8 ?? ?? ?? ?? 48 85 C0 75 ?? 49 8B 04 DE 8B 40 04 85 C0 74 ?? FF C6 49 81 C3 ?? ?? ?? ?? 83 FE 04 72 ?? BA 11 34 75 97 E8 ?? ?? ?? ?? 48 8B CF E8 ?? ?? ?? ?? 8B 87 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? 48 69 D0 ?? ?? ?? ?? 48 83 C2 ?? 48 03 D7 E8 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 87 ?? ?? ?? ?? 48 69 C8 ?? ?? ?? ?? 48 83 C1 ?? 48 03 CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 83 FE FF 74 ?? 48 8D 8F ?? ?? ?? ?? 8B D6 E8 ?? ?? ?? ?? 89 B7 ?? ?? ?? ??',
     fields = {panels = {'u32', {3}}, slots_changed = {'call', {15}, {19}}, refresh = {'call', {157}, {161}}, list_grid = {'u32', {164}}, grid_refresh = {'call', {169}, {173}}, block_stride = {'u32', {145, 182}}, block_base = {'u8', {152, 189}}, save = {'call', {194}, {198}}, grid_mode = {'u32', {21}}, slot_types = {'u32', {38}}, slot_stride = {'u32', {102}}, ui_sound = {'call', {117}, {121}}, close_list = {'call', {125}, {129}}, local_index = {'u32', {131, 175}}, list = {'u32', {138}}, grid = {'u32', {211}}, focus_call = {'call', {218}, {222}}, edit_slot = {'u32', {224}}}},
    {name = 'open_list', rva = 0x146e9d0, optional = true, text = '40 57 48 81 EC A0 00 00 00 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 44 24 70 80 B9 08 28 00 00 00 48 8B F9 0F 85 ?? ?? ?? ?? F7 81 D8 F2 0C 00 00 00 00 08 74 ?? 8B 81 88 F3 0C 00 48 C1 E8 0B A9 FF 07 00 00 0F 85 ?? ?? ?? ?? 0F B6 81 91 39 27 00 48 89 9C 24 B0 00 00 00 48 8D 99 ?? ?? ?? ?? 48 89 AC 24 B8 00 00 00 BD 04 00 00 00 48 89 B4 24 C0 00 00 00 8B F5 0F 29 BC 24 90 00 00 00 44 0F 29 84 24 80 00 00 00 C6 81 ?? ?? ?? ?? 01 88 81 92 39 27 00',
     fields = {panels = {'u32', {91}}, list_open = {'u32', {137}}}},
    {name = 'set_slot', rva = 0x189d050, optional = true, text = '83 FA 04 0F 83 ?? ?? ?? ?? 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 41 8B D8 8B F2 48 8D B9 78 5B 00 00 8B CB E8 ?? ?? ?? ?? 48 69 CE ?? ?? ?? ?? 8B D0 48 81 C1 ?? ?? ?? ?? 48 03 CF E8 ?? ?? ?? ?? 80 BF 78 D9 00 00 00',
     fields = {slot_stride = {'u32', {46}}, widget_base = {'u32', {55}}, set_widget = {'call', {63}, {67}}}},
    {name = 'list_update', rva = 0x18cf84f, optional = true, text = 'F3 0F 10 81 ?? ?? ?? ?? F3 0F 58 C1 0F 2F C8 F3 0F 11 81 ?? ?? ?? ?? 76 ?? C7 81 ?? ?? ?? ?? 00 00 00 00 EB ?? F3 0F 10 89 ?? ?? ?? ?? 0F 2F C1 76 ?? F3 0F 11 89 ?? ?? ?? ?? F3 0F 10 81 6C 29 09 00 F3 0F 59 05 ?? ?? ?? ?? C7 81 70 29 09 00 00 00 00 40 F3 0F 11 81 6C 29 09 00 48 81 C1 00 29 09 00 0F 28 CE E8 ?? ?? ?? ?? 0F B6 83 FA 28 09 00 0F B6 8B 02 29 09 00 88 8B FA 28 09 00 84 C0 75 ?? 84 C9 74 ?? 80 BB F8 28 09 00 00 74 ?? F3 0F 10 83 C8 08 00 00 F3 0F 59 83 ?? ?? ?? ?? F3 0F 11 83 ?? ?? ?? ?? 48 8B CB E8 ?? ?? ?? ??',
     fields = {scroll = {'u32', {4, 19, 27, 54, 164}}, scroll_max = {'u32', {41, 156}}, layout = {'call', {172}, {176}}}},
    {name = 'list_focus', rva = 0x18d1280, optional = true, text = '48 89 5C 24 18 55 56 57 48 83 EC 20 44 8B 89 14 1F 09 00 33 ED 48 8B F9 44 8B C5 8B F5 45 85 C9 74 ?? 0F 1F 40 00 66 66 0F 1F 84 00 00 00 00 00 8B C6 8B DD 8B 8C 87 18 23 09 00 85 C9 74 ?? 90 41 8B C0 39 94 87 ?? ?? ?? ?? 74 ?? 41 FF C0 FF C3 3B D9 72 ?? FF C6 41 3B F1',
     fields = {ids = {'u32', {70}}}},
    {name = 'focus', rva = 0x1895770, optional = true, text = '48 89 5C 24 08 57 48 83 EC 20 8B 81 ?? ?? ?? ?? 48 8B F9 8B DA 3B C2',
     fields = {grid_focus = {'u32', {12}}}},
}
-- END SIGNATURES

-- BEGIN SIGNATURE ENGINE (tools/sigscan.lua, written by research/signatures.py: edit it there)
-- Signature engine v1: finds game.dll code by signatures and reads values from the matched code.
-- Canonical copy: tools/sigscan.lua in the workspace. Each mod's research/signatures.py writes this block and the
-- mod's SIGS table into its script (tools/sigspec.py), so every mod carries the same engine.
--
-- A signature is {name, rva, text, fields, optional}: text is hex bytes with '??' wildcards; rva is where the
-- generating build had it. fields = {field = {kind, {offset...}, {next...}}}: kind 'u8' / 'u32' (a value inside the
-- matched code), 'rip' (a global: the target of a rip-relative operand) or 'call' (a function: the target of a rel32
-- call); offset = each occurrence's byte position in the pattern, next = the end of its instruction. Every occurrence
-- must agree, and a field shared by several signatures must agree across them.
--
--   local code = sigscan.new(SIGS, read, base, validate)  -- read(address, size) -> string or nil; base = game.dll
--                                                        -- base; validate (optional) = {name = function(rva) -> bool}:
--                                                        -- extra checks a match must pass (decoys don't count)
--   code:start()                                 -- tries each signature at its rva; true when all were there
--   code:step()                                  -- else: one chunk of the search per call; true when finished
--   code.found[name] (rva), code.missing[name] (reason), code.values[field], code.problems (list)
local sigscan = {}
do
    local CHUNK, OVERLAP = 0x400000, 256

    local function u16(b, o) return b:byte(o + 1) + 256 * b:byte(o + 2) end
    local function u32(b, o)
        local x1, x2, x3, x4 = b:byte(o + 1, o + 4)
        return x1 + 256 * x2 + 65536 * x3 + 16777216 * x4
    end
    local function i32(b, o)
        local v = u32(b, o)
        return v >= 2147483648 and v - 4294967296 or v
    end

    local function parse(sig)
        local bytes = {}
        for part in sig.text:gmatch('%S+') do bytes[#bytes + 1] = part ~= '??' and tonumber(part, 16) or false end
        local best_at, best_len, at, len = 1, 0, nil, 0  -- the longest run of fixed bytes is searched for
        for i = 1, #bytes + 1 do
            if bytes[i] then
                if not at then at, len = i, 0 end
                len = len + 1
                if len > best_len then best_at, best_len = at, len end
            else
                at = nil
            end
        end
        local anchor = {}
        for i = best_at, best_at + best_len - 1 do anchor[#anchor + 1] = string.char(bytes[i]) end
        sig.bytes, sig.anchor, sig.anchor_at = bytes, table.concat(anchor), best_at - 1
    end

    local function matches(blob, pos, sig)  -- pos: 1-based start in blob
        local bytes = sig.bytes
        if pos < 1 or pos + #bytes - 1 > #blob then return false end
        for i = 1, #bytes do
            local b = bytes[i]
            if b and blob:byte(pos + i - 1) ~= b then return false end
        end
        return true
    end

    local Scanner = {}
    Scanner.__index = Scanner

    function sigscan.new(sigs, read, base, validate)
        return setmetatable({sigs = sigs, read = read, base = base, validate = validate or {}, found = {}, missing = {},
                             moved = {}, values = {}, problems = {}, scan = nil, done = false}, Scanner)
    end

    function Scanner:valid(name, rva)
        local check = self.validate[name]
        if not check then return true end
        local ok, good = pcall(check, rva)
        return ok and good and true or false
    end

    -- game.dll's sections: {rva, size, exec}.
    function Scanner:load_sections()
        local read, base = self.read, self.base
        local dos = read(base, 0x40)
        local pe = dos and dos:sub(1, 2) == 'MZ' and u32(dos, 0x3c)
        local nt = pe and pe < 0x10000 and read(base + pe, 0x18)
        if not nt or nt:sub(1, 4) ~= 'PE\0\0' then return nil end
        local count, opt = u16(nt, 6), u16(nt, 20)
        local headers = count <= 96 and read(base + pe + 24 + opt, count * 40)
        if not headers then return nil end
        local sections = {}
        for i = 0, count - 1 do
            local size, rva, flags = u32(headers, i * 40 + 8), u32(headers, i * 40 + 12), u32(headers, i * 40 + 36)
            if size > 0 then
                sections[#sections + 1] = {rva = rva, size = size, exec = math.floor(flags / 0x20000000) % 2 == 1}
            end
        end
        return sections
    end

    function Scanner:in_section(rva, exec)
        for _, s in ipairs(self.sections) do
            if s.exec == exec and rva >= s.rva and rva + 8 <= s.rva + s.size then return true end
        end
        return false
    end

    -- Tries every signature at its rva and starts a search for the others. True when all were there (done), false
    -- when a search started, nil and a reason when game.dll is unreadable.
    function Scanner:start()
        self.sections = self:load_sections()
        if not self.sections then return nil, 'game.dll headers unreadable' end
        local wanted = {}
        for _, sig in ipairs(self.sigs) do
            parse(sig)
            local blob = self.read(self.base + sig.rva, #sig.bytes)
            if blob and matches(blob, 1, sig) and self:valid(sig.name, sig.rva) then
                self.found[sig.name] = sig.rva
            else
                wanted[#wanted + 1] = sig
            end
        end
        if #wanted == 0 then
            self:resolve()
            return true
        end
        local exec = {}
        for _, s in ipairs(self.sections) do if s.exec then exec[#exec + 1] = s end end
        self.scan = {sections = exec, section = 1, offset = 0, wanted = wanted, hits = {}}
        for _, sig in ipairs(wanted) do self.scan.hits[sig.name] = {} end
        return false
    end

    -- One chunk of the search (every match is collected: a signature must match exactly once). True when finished.
    function Scanner:step()
        local scan = self.scan
        if not scan then return true end
        local s = scan.sections[scan.section]
        if s then
            local from = scan.offset
            local size = math.min(CHUNK + OVERLAP, s.size - from)
            local pieces = {}
            local blob = self.read(self.base + s.rva + from, size)
            if blob then
                pieces[1] = {from, blob}
            else
                for off = from, from + size - 1, 0x10000 do  -- skip unreadable pages
                    local piece = self.read(self.base + s.rva + off, math.min(0x10000 + OVERLAP, s.size - off))
                    if piece then pieces[#pieces + 1] = {off, piece} end
                end
            end
            for _, piece in ipairs(pieces) do
                local piece_from, data = piece[1], piece[2]
                for _, sig in ipairs(scan.wanted) do
                    local init = 1
                    while true do
                        local at = data:find(sig.anchor, init, true)
                        if not at then break end
                        local start = at - sig.anchor_at
                        local offset = piece_from + start - 1
                        -- Matches starting in the overlap belong to the next chunk.
                        if offset >= from and offset < from + CHUNK and matches(data, start, sig)
                           and self:valid(sig.name, s.rva + offset) then
                            local hits = scan.hits[sig.name]
                            hits[#hits + 1] = s.rva + offset
                        end
                        init = at + 1
                    end
                end
            end
            scan.offset = from + CHUNK
            if scan.offset >= s.size then scan.section, scan.offset = scan.section + 1, 0 end
            if scan.sections[scan.section] then return false end
        end
        for _, sig in ipairs(scan.wanted) do
            local hits = scan.hits[sig.name]
            if #hits == 1 then
                self.found[sig.name] = hits[1]
                self.moved[#self.moved + 1] = sig.name
            else
                self.missing[sig.name] = #hits == 0 and 'not found' or ('found ' .. #hits .. ' times')
            end
        end
        self.scan = nil
        self:resolve()
        return true
    end

    -- A field's value from the matched code; nil and a reason if its occurrences disagree or it points nowhere.
    function Scanner:field_value(sig, rva, spec)
        local blob = self.read(self.base + rva, #sig.bytes)
        if not blob then return nil, 'unreadable' end
        local value
        for k, off in ipairs(spec[2]) do
            local v
            if spec[1] == 'u8' then v = blob:byte(off + 1)
            elseif spec[1] == 'u32' then v = u32(blob, off)
            else v = rva + spec[3][k] + i32(blob, off) end
            if value and v ~= value then return nil, 'occurrences disagree' end
            value = v
        end
        if spec[1] == 'rip' and not self:in_section(value, false) then return nil, 'global not in a data section' end
        if spec[1] == 'call' and not self:in_section(value, true) then return nil, 'function not in a code section' end
        return value
    end

    -- Reads every field of the found signatures. A signature whose fields don't read becomes missing; a field that
    -- differs between signatures is dropped (nil) and listed in problems.
    function Scanner:resolve()
        local seen = {}
        for _, sig in ipairs(self.sigs) do
            local rva = self.found[sig.name]
            if rva then
                local got = {}
                for name, spec in pairs(sig.fields or {}) do
                    local v, why = self:field_value(sig, rva, spec)
                    if not v then
                        self.missing[sig.name] = string.format('field "%s" %s', name, why)
                        self.found[sig.name] = nil
                        got = nil
                        break
                    end
                    got[name] = v
                end
                for name, v in pairs(got or {}) do
                    if seen[name] ~= nil and seen[name] ~= v then
                        self.problems[#self.problems + 1] = string.format('"%s" differs between signatures', name)
                        seen[name] = false
                    elseif seen[name] == nil then
                        seen[name] = v
                    end
                end
            end
        end
        for name, v in pairs(seen) do self.values[name] = v or nil end
        self.done = true
    end

    -- The address of a found signature's match (plus an offset), or nil.
    function Scanner:address(name, offset)
        local rva = self.found[name]
        return rva and self.base + rva + (offset or 0)
    end

    -- Every missing signature as 'name (reason)', for logs and status files.
    function Scanner:missing_list()
        local out = {}
        for _, sig in ipairs(self.sigs) do
            if self.missing[sig.name] then out[#out + 1] = sig.name .. ' (' .. self.missing[sig.name] .. ')' end
        end
        return out
    end
end
-- END SIGNATURE ENGINE

-- Values the signatures don't carry: the loadout screen's type on the screen stack (+0), the stratagems category,
-- and bounds for the sanity checks.
local LOADOUT_SCREEN, STRATAGEMS = 11, 10
local BLOCK_MAX, ENTRY_SIZE, LIST_MAX = 32, 0x30, 256   -- entry size and offer entry layout are literal in refresh_a/b
local OFFER_STRIDE, OFFER_ID, OFFER_ITEM, INFO_ID = 0x18, 4, 8, 4
local VEHICLE_BITS = 0x700000                            -- literal in kind_mech / kind_frv / kind_tank
local IDLE_POLL = 10       -- frames between loadout screen checks while it is not open
local REQUIRED = {'screen', 'category', 'refresh_call', 'refresh_a', 'refresh_b', 'offers_count', 'marker', 'select',
                  'kind_frv', 'kind_mech', 'kind_tank'}

-- Copies of one stratagem a loadout may hold: the Mod Options Menu slider (4 copies: no limit in 4 slots).
local COPIES = {min = 2, max = 4, default = 2}
local OPTION_ID = 'alomare.flexible_stratagems.max_copies'
-- Literal in the ready signatures: a slot's type (+4 from its flags), the local player's flag byte (entry + 0x14),
-- the players' flag stride, and the ready bits (3: ready, 11: also counted as ready by the handler).
local SLOT_TYPE, PLAYER_LOCAL, PLAYER_STRIDE, READY_BIT, READY_ALSO = 4, 0x14, 0x20, 8, 0x800
local READY_SIGS = {'ready_call', 'ready_slots', 'ready_toggle'}
local ADVANCE_SIGS = {'equip_tail', 'open_list', 'focus'}
local SCROLL_SIGS = {'list_update', 'list_focus'}
local CLEAR_SIGS = {'equip_tail', 'set_slot'}
local CLEAR_BINDING = 'alomare.flexible_stratagems.clear'

---------------------------------------------------------------------------------------
-- Logging and status

local function open_log(name)
    if loader and type(loader.open_log) == 'function' then
        local ok, f = pcall(loader.open_log, name)
        if ok then return f end
    end
end

local log_file = open_log('FlexibleStratagems.log')
local log_lines = 0

local function note(msg)
    if not log_file or log_lines >= 1000 then return end
    log_lines = log_lines + 1
    pcall(function()
        log_file:write(string.format('[f%d] %s\n', M.frames, msg))
        log_file:flush()
    end)
end

local function write_status(verdict, details)
    local f = open_log('FlexibleStratagems_STATUS.log')
    if not f then return end
    pcall(function()
        f:write(verdict .. '\nFlexible Stratagems ' .. M.version .. '\n')
        for _, line in ipairs(details or {}) do f:write(line .. '\n') end
        f:close()
    end)
end

---------------------------------------------------------------------------------------
-- Texts (mod_text: src/bingus_text.lua and locales/, placed ahead of this script by the build)

local T = mod_text.module
local tr = T.new(mod_text.locales.en, mod_text.locales.bundled, function(message) note('Text: ' .. message) end)

---------------------------------------------------------------------------------------
-- Native memory. The per-frame reads go into fixed buffers; the rest (start, once per screen visit) allocate.

local native = {}

local function init_native()
    for _, decl in ipairs({
        'void *GetCurrentProcess(void);',
        'void *GetModuleHandleA(const char *name);',
        'int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);',
        'int WriteProcessMemory(void *process, void *address, const void *buffer, size_t size, size_t *written);',
    }) do pcall(ffi.cdef, decl) end
    local ok, k32 = pcall(ffi.load, 'kernel32')
    if not ok then return false, 'kernel32 unavailable' end
    native.k32, native.process = k32, k32.GetCurrentProcess()
    local game = k32.GetModuleHandleA('game.dll')
    if game == nil then return false, 'game.dll not loaded' end
    native.base = tonumber(ffi.cast('uint64_t', game))
    return true
end

local got = ffi.new('size_t[1]')

local function read_into(buf, address, size)
    return native.k32.ReadProcessMemory(native.process, ffi.cast('const void *', address), buf, size, got) ~= 0
           and tonumber(got[0]) == size
end

local function read(address, size)
    local buf = ffi.new('uint8_t[?]', size)
    if not read_into(buf, address, size) then return nil end
    return ffi.string(buf, size)
end

local function write(address, bytes)
    local ok = native.k32.WriteProcessMemory(native.process, ffi.cast('void *', address), bytes, #bytes, got)
    return ok ~= 0 and tonumber(got[0]) == #bytes
end

local function u32(blob, offset)
    offset = offset or 0
    if not blob or #blob < offset + 4 then return nil end
    local v = ffi.new('uint32_t[1]')
    ffi.copy(v, blob:sub(offset + 1, offset + 4), 4)
    return tonumber(v[0])
end

local function pointer_value(v)
    local a = tonumber(v)
    if a < 0x10000 or a >= 0x800000000000 then return nil end
    return a
end

local function pointer(blob)
    if not blob or #blob < 8 then return nil end
    local v = ffi.new('uint64_t[1]')
    ffi.copy(v, blob, 8)
    return pointer_value(v[0])
end

local function global(rva) return pointer(read(native.base + rva, 8)) end

local function u32_bytes(v) return ffi.string(ffi.new('uint32_t[1]', v), 4) end
local function u64_bytes(v) return ffi.string(ffi.new('uint64_t[1]', v), 8) end

-- Views into the fixed buffers.
local function buf_u32(buf, offset) return tonumber(ffi.cast('uint32_t *', buf + offset)[0]) end
local function buf_u64(buf, offset) return tonumber(ffi.cast('uint64_t *', buf + offset)[0]) end  -- exact below 2^53
local function buf_pointer(buf, offset) return pointer_value(ffi.cast('uint64_t *', buf + offset)[0]) end

---------------------------------------------------------------------------------------
-- The layout, from the matched code

local code = nil  -- the signature engine
local L = {}      -- field name -> value (offsets) or rva (globals, functions)
local SCREEN, LIST, BLOCK = {}, {}, {}

-- Checks the pieces fit together (the engine already made every field agree across signatures).
local function read_layout()
    for _, name in ipairs(REQUIRED) do
        if not code.found[name] then return false, string.format('code "%s" %s', name, code.missing[name] or 'not found') end
    end
    if #code.problems > 0 then return false, code.problems[1] end
    for k, v in pairs(code.values) do L[k] = v end
    local found = code.found
    -- The functions: the refresh the handler calls holds refresh_a/b and calls the marker found on its own.
    if L.mark ~= found.marker then return false, 'the refresh does not call the marker' end
    for _, part in ipairs({'refresh_a', 'refresh_b'}) do
        if found[part] < L.refresh or found[part] > L.refresh + 0x1000 then return false, part .. ' outside the refresh' end
    end
    -- The spans read each frame: the screen head (local index .. category), the list (count .. selectable bytes),
    -- a loadout block (entries .. count).
    if L.category <= L.local_index or L.category - L.local_index > 0x1000 then return false, 'screen head layout' end
    SCREEN.head, SCREEN.head_size = L.local_index, L.category - L.local_index + 4
    SCREEN.local_index, SCREEN.category = 0, L.category - L.local_index
    SCREEN.blocks, SCREEN.block_size, SCREEN.list = L.block_base, L.block_stride, L.list
    LIST.span, LIST.count = L.list_count, 0
    LIST.selected, LIST.ids, LIST.selectable = L.selected - L.list_count, L.ids - L.list_count, L.selectable - L.list_count
    LIST.span_size = LIST.selectable + LIST_MAX
    for _, k in ipairs({'selected', 'ids', 'selectable'}) do
        if LIST[k] < 4 or LIST[k] > 0x1000 then return false, 'list layout (' .. k .. ')' end
    end
    if LIST.ids + LIST_MAX * 4 > LIST.selectable then return false, 'list layout (ids)' end
    BLOCK.entries, BLOCK.count = L.block_entries, L.block_count
    if BLOCK.count < BLOCK.entries + BLOCK_MAX * ENTRY_SIZE or BLOCK.count >= SCREEN.block_size then
        return false, 'loadout block layout'
    end
    if L.types < 2 or L.types > 0x1000 then return false, 'stratagem table size' end
    return true
end

-- The list extras (ready with empty slots, the list kept open after a replacement and its scroll, the
-- clear key): each is on only when all its code is found and fits; otherwise only that extra is off.
local EXTRA = {ready = false, advance = false, scroll = false, clear = false}
local WIDGET = {}  -- the slot widgets: offset from the grid, type offset

local function read_extras()
    local found = code.found
    local function missing(names)
        for _, name in ipairs(names) do
            if not found[name] then return string.format('code "%s" %s', name, code.missing[name] or 'not found') end
        end
    end
    local why = missing(READY_SIGS)
    if not why then
        for _, part in ipairs({'ready_slots', 'ready_toggle'}) do
            if found[part] < L.ready_handler or found[part] > L.ready_handler + 0x800 then
                why = part .. ' outside the ready handler'
            end
        end
    end
    if not why and (L.slot_stride < 0x100 or L.slot_stride > 0x10000 or L.flash >= L.slot_stride) then why = 'slot layout' end
    if not why then
        local ok, fn = pcall(ffi.cast, 'void (*)(uint64_t, uint32_t)', native.base + L.ui_sound)
        if ok then native.sound = fn else why = 'native function sound unavailable' end
    end
    EXTRA.ready, EXTRA.ready_why = not why, why
    why = missing(ADVANCE_SIGS)
    if not why and L.focus_call ~= found.focus then why = 'the equip handler does not focus with the setter found' end
    if not why and L.slot_flags and L.slot_types ~= L.panels + L.slot_flags + SLOT_TYPE then why = 'slot layout' end
    if not why then
        SCREEN.edit = L.edit_slot - L.local_index
        if SCREEN.edit < 0 or SCREEN.edit > 0x1000 then why = 'screen head layout (edited slot)' end
    end
    if not why then
        local ok1, open = pcall(ffi.cast, 'void (*)(uint64_t)', code:address('open_list'))
        local ok2, focus = pcall(ffi.cast, 'void (*)(uint64_t, uint32_t)', code:address('focus'))
        if ok1 and ok2 then native.open, native.focus = open, focus else why = 'native functions unavailable' end
    end
    if not why then SCREEN.head_size = math.max(SCREEN.head_size, SCREEN.edit + 4) end
    EXTRA.advance, EXTRA.advance_why = not why, why
    -- The scroll kept when the list opens again.
    why = (not EXTRA.advance and 'needs the list kept open') or missing(SCROLL_SIGS)
    if not why then
        local ok1, layout = pcall(ffi.cast, 'void (*)(uint64_t)', native.base + L.layout)
        local ok2, list_focus = pcall(ffi.cast, 'uint8_t (*)(uint64_t, uint32_t)', code:address('list_focus'))
        if ok1 and ok2 then native.layout, native.list_focus = layout, list_focus else why = 'native functions unavailable' end
    end
    EXTRA.scroll, EXTRA.scroll_why = not why, why
    -- Clear Stratagems: the slot widgets (grid + widget base + slot * stride, type at +0x128c on this build).
    why = missing(CLEAR_SIGS)
    if not why then
        WIDGET.base = L.grid + L.widget_base
        WIDGET.type = L.slot_types - WIDGET.base
        if WIDGET.type < 4 or WIDGET.type >= L.slot_stride then why = 'slot widget layout' end
        if not why and L.slot_flags and L.slot_flags + SLOT_TYPE ~= L.slot_types - L.panels then why = 'slot widget layout' end
    end
    if not why then
        local casts = {set_widget = {'void (*)(uint64_t, uint32_t)', L.set_widget},
                       slots_changed = {'void (*)(uint64_t, int64_t)', L.slots_changed},
                       save = {'void (*)(uint64_t)', L.save}, close = {'void (*)(uint64_t)', L.close_list}}
        for name, c in pairs(casts) do
            local ok, fn = pcall(ffi.cast, c[1], native.base + c[2])
            if ok then native[name] = fn else why = 'native function ' .. name .. ' unavailable' end
        end
    end
    EXTRA.clear, EXTRA.clear_why = not why, why
end

---------------------------------------------------------------------------------------
-- Stratagem data

local function info_of(t)  -- the stratagem's info (its type at +0), from the game's stratagem table
    local info = t and t > 0 and t < L.types and global(L.strat_table + t * 8)
    if info and u32(read(info, 4)) == t then return info end
end

local function item_id(t)  -- the stratagem's item id (info +4)
    local info = info_of(t)
    return info and u32(read(info + INFO_ID, 4))
end

-- Stratagem item id -> offer id, from the offers table's stratagem range (built once per screen visit).
local function offer_map()
    local map = {}
    local offers = global(L.offers)
    local first = offers and u32(read(offers + L.first, 4))
    local last = offers and u32(read(offers + L.last, 4))
    local count = offers and u32(read(offers + L.offers_count, 4))
    if not first or not last or not count or last <= first or last - first > 512 or count > 0x10000 then return map end
    local indices = read(offers + L.indices + first * 4, (last - first) * 4)
    for k = 0, last - first - 1 do
        local index = u32(indices, k * 4)
        local entry = index and index < count and read(offers + L.entries + index * OFFER_STRIDE, OFFER_STRIDE)
        if entry then map[u32(entry, OFFER_ITEM)] = u32(entry, OFFER_ID) end
    end
    return map
end

---------------------------------------------------------------------------------------
-- Settings: the copy limit (Mod Options Menu, which may load before or after this addon)

local settings = {max_copies = COPIES.default, menu = nil, dirty = false}  -- dirty: status to rewrite

-- Mod Options Menu v1.1 and later (version 2) take texts as functions and call them whenever the escape menu opens,
-- so they follow the game's language; v1.0 takes strings with byte limits, where a translation that does not fit
-- stays English.
local text_functions = {}
local function host_text(menu, functions_from, key, bytes)
    if (tonumber(menu.version) or 1) >= functions_from then
        local fn = text_functions[key]
        if not fn then fn = function() return tr(key) end; text_functions[key] = fn end
        return fn
    end
    local value = tr(key)
    return #value <= bytes and value or tr.english[key]
end

local function option_text(menu, key, bytes) return host_text(menu, 2, key, bytes) end

local copies_changed  -- defined with the list below

local function set_max_copies(value)
    value = math.floor(tonumber(value) or COPIES.default)
    value = math.max(COPIES.min, math.min(COPIES.max, value))
    if value == settings.max_copies then return end
    note('Copies per stratagem: ' .. value)
    settings.max_copies = value
    copies_changed()
end

local function connect_menu()
    local menu = rawget(_G, 'ModOptionsMenu')
    if type(menu) ~= 'table' or menu.api ~= 1 then return false end
    settings.menu = menu
    local ok, done, why = pcall(menu.register_option, OPTION_ID, {
        type = 'slider', mod = option_text(menu, 'option.mod', 40), label = option_text(menu, 'option.copies.label', 64),
        min = COPIES.min, max = COPIES.max, step = 1, default = COPIES.default,
        description = option_text(menu, 'option.copies.description', 400)})
    if ok and done then
        pcall(menu.on_change, OPTION_ID, function(value) set_max_copies(value) end)
        local read_ok, value = pcall(menu.get, OPTION_ID)
        set_max_copies(read_ok and value)
        note('Mod Options Menu connected (version ' .. tostring(menu.version or 1) .. ')')
    else
        note('Option not registered: ' .. tostring(ok and why or done))
    end
    return true
end

---------------------------------------------------------------------------------------
-- The vehicle rule: kind bits cleared while the list is open, restored after.

local vehicles = nil      -- {{info address, original flags, cleared flags}...}, found once
local vehicles_lifted = false

local function find_vehicles()
    local found = {}
    for t = 1, L.types - 1 do
        local info = global(L.strat_table + t * 8)
        local flags = info and u32(read(info, 4)) == t and u32(read(info + L.flags, 4))
        if flags and bit.band(flags, VEHICLE_BITS) ~= 0 then
            local cleared = bit.band(flags, bit.bnot(VEHICLE_BITS))
            if cleared < 0 then cleared = cleared + 4294967296 end
            found[#found + 1] = {info, flags, cleared}
        end
    end
    return found
end

local function lift_vehicles()
    if vehicles_lifted then return end
    vehicles_lifted = true
    vehicles = vehicles or find_vehicles()
    for _, v in ipairs(vehicles) do
        if u32(read(v[1] + L.flags, 4)) ~= v[2] then  -- the table moved or changed: look again
            vehicles = find_vehicles()
            break
        end
    end
    for _, v in ipairs(vehicles) do write(v[1] + L.flags, u32_bytes(v[3])) end
end

local function restore_vehicles()
    if not vehicles_lifted then return end
    vehicles_lifted = false
    for _, v in ipairs(vehicles or {}) do
        -- Only what still holds our value (never overwrite something the game changed meanwhile).
        if u32(read(v[1] + L.flags, 4)) == v[3] then write(v[1] + L.flags, u32_bytes(v[2])) end
    end
end

---------------------------------------------------------------------------------------
-- The stratagem list

local buffers = {}  -- sized from the layout once it is known
local visit = {offers = nil, block = nil, refused = nil}  -- per loadout screen visit

local function make_buffers()
    buffers.global = ffi.new('uint8_t[8]')
    buffers.stack = ffi.new('uint8_t[?]', L.slot + 8)
    buffers.head = ffi.new('uint8_t[?]', SCREEN.head_size)
    buffers.list = ffi.new('uint8_t[?]', LIST.span_size)
    buffers.block = ffi.new('uint8_t[?]', BLOCK.count - BLOCK.entries + 4)
    buffers.byte = ffi.new('uint8_t[1]')
end

-- The loadout's stratagems as {offer id = copies}, plus the entries as a string (to notice picks).
local function loadout_offers(screen, index)
    local block = screen + SCREEN.blocks + index * SCREEN.block_size
    if not read_into(buffers.block, block + BLOCK.entries, BLOCK.count - BLOCK.entries + 4) then return nil end
    local count = buf_u32(buffers.block, BLOCK.count - BLOCK.entries)
    if count > BLOCK_MAX then return nil end
    visit.offers = visit.offers or offer_map()
    local copies = {}
    for e = 0, count - 1 do
        local offer = visit.offers[item_id(buf_u32(buffers.block, e * ENTRY_SIZE))]
        if offer then copies[offer] = (copies[offer] or 0) + 1 end
    end
    return copies, ffi.string(buffers.block, count * ENTRY_SIZE)
end

local function service_list(screen, index)
    local list = screen + SCREEN.list
    local list_buf = buffers.list
    if not read_into(list_buf, list + LIST.span, LIST.span_size) then return end
    local n = buf_u32(list_buf, LIST.count)
    if n == 0 or n > LIST_MAX then restore_vehicles(); return end
    lift_vehicles()
    -- Refused items: none in steady state (the loadout's are marked back); after a pick the refresh refuses the
    -- loadout's again. The same refused set as last time (other reasons, or the copy limit) is left alone without
    -- reading more.
    local refused = nil
    for i = 0, n - 1 do
        if list_buf[LIST.selectable + i] == 0 then
            refused = refused or {}
            refused[#refused + 1] = i
        end
    end
    if not refused then visit.refused = nil; return end
    local key = table.concat(refused, ',')
    if key == visit.refused then return end
    local copies, block = loadout_offers(screen, index)
    if not copies then return end
    if visit.block and block ~= visit.block then
        -- A pick: a selection left on a loadout stratagem would silence the next pick of it.
        local selected = buf_u32(list_buf, LIST.selected)
        if selected ~= 0 and copies[selected] then native.select(list, 0) end
    end
    visit.block = block
    local limit = settings.max_copies
    local kept = {}
    for _, i in ipairs(refused) do
        local offer = buf_u32(list_buf, LIST.ids + i * 4)
        if copies[offer] and copies[offer] < limit then
            native.mark(list, offer, 1)
        else
            kept[#kept + 1] = i
        end
    end
    visit.refused = #kept > 0 and table.concat(kept, ',') or nil
end

copies_changed = function()
    -- The refused items are looked at again under the new limit.
    visit.refused = nil
    settings.dirty = true
end

---------------------------------------------------------------------------------------
-- Ready with empty slots

local ready = {flash = nil, now = {}}  -- the local panel's slot flash bytes last frame (nil: not watched)

-- Whether every other player is ready, as the handler decides which ready sound plays.
local function others_ready(panel, players)
    local count = u32(read(players + L.player_count, 4))
    local own = u32(read(panel + L.panel_entity, 4))
    if not count or count > 16 then return false end
    for i = 0, count - 1 do
        local entry = pointer(read(players + L.player_entries + i * 8, 8))
        if not entry or u32(read(entry + 8, 4)) ~= own then
            local flags = u32(read(players + L.player_flags + i * PLAYER_STRIDE, 4)) or 0
            if bit.band(flags, READY_BIT + READY_ALSO) == 0 then return false end
        end
    end
    return true
end

-- The handler's toggle for the local panel: an idle timer starts the ready (the panel update sets the ready bit when
-- it runs out); otherwise the ready is cancelled (the refusal already played the cancel sound, the same one).
local function toggle_ready(panel, empty)
    local own = read(panel + L.panel_local, 1)
    local timer = u32(read(panel + L.ready_timer, 4))
    local players = global(L.players)
    if not own or own:byte() == 0 or not timer or not players then return end
    if timer == L.timer_idle then
        local last = others_ready(panel, players)
        write(panel + L.ready_timer, u32_bytes(L.ready_time))
        native.sound(0, last and L.sound_ready_last or L.sound_ready)
        note(string.format('Ready with %d empty slot(s)%s', empty, last and ' (last player)' or ''))
        return
    end
    write(panel + L.ready_timer, u32_bytes(L.timer_idle))
    local entries = pointer(read(players + L.player_entries, 8))
    local mine = entries and read(entries + PLAYER_LOCAL, 1)
    local flags = u32(read(players + L.player_flags, 4))
    if (u32(read(players + L.player_active, 4)) or 0) >= 1 and mine and mine:byte() % 2 == 1 and flags
       and bit.band(flags, READY_BIT) ~= 0 then
        write(players + L.player_flags, u32_bytes(flags - READY_BIT))
    end
    note(string.format('Ready cancelled (%d empty slot(s))', empty))
end

-- While the list is closed: a flash starting on an empty slot is the handler refusing a ready press.
local function service_ready(screen, list_open)
    if list_open then ready.flash = nil; return end
    local base = screen + L.panels + L.slot_flags + L.flash
    local now, started, flashing = ready.now, false, 0
    for k = 0, 3 do
        if not read_into(buffers.byte, base + k * L.slot_stride, 1) then ready.flash = nil; return end
        now[k] = buffers.byte[0]
        if now[k] ~= 0 then
            flashing = flashing + 1
            if ready.flash and ready.flash[k] == 0 then started = true end
        end
    end
    ready.now, ready.flash = ready.flash or {}, now
    if started then toggle_ready(screen + L.panels, flashing) end
end

---------------------------------------------------------------------------------------
-- The list kept open after a replacement

-- While the list is open: the edited slot, the loadout and the list's scroll.
local advance = {slot = nil, count = nil, block = nil, scroll = nil}

local function loadout_block(screen, index)
    local block = screen + SCREEN.blocks + index * SCREEN.block_size
    if not read_into(buffers.block, block + BLOCK.entries, BLOCK.count - BLOCK.entries + 4) then return nil end
    local count = buf_u32(buffers.block, BLOCK.count - BLOCK.entries)
    if count > BLOCK_MAX then return nil end
    return count, ffi.string(buffers.block, count * ENTRY_SIZE)
end

local function service_advance(screen, index, list_open, category)
    if list_open then
        if category ~= STRATAGEMS then advance.slot = nil; return end
        advance.slot = buf_u32(buffers.head, SCREEN.edit)
        advance.count, advance.block = loadout_block(screen, index)
        advance.scroll = EXTRA.scroll and read(screen + L.list + L.scroll, 4) or nil
        return
    end
    local slot = advance.slot
    if slot == nil then return end
    advance.slot = nil
    -- Closed by a pick (the loadout changed) that left all four filled, from slot 1 to 3: the next slot.
    local count, block = loadout_block(screen, index)
    if not (count == 4 and advance.count == 4 and block ~= advance.block and slot < 3) then return end
    if u32(read(screen + L.grid_mode, 4)) == 1 then return end
    native.focus(screen + L.grid, slot + 1)
    native.open(screen)
    note(string.format('Replaced slot %d: list opened on slot %d', slot + 1, slot + 2))
    if not (EXTRA.scroll and advance.scroll) then return end
    -- Where the player was: the stratagem just picked focused, the scroll as it was before the list closed.
    local list = screen + L.list
    local picked = u32(read(screen + L.slot_types + slot * L.slot_stride, 4))
    visit.offers = visit.offers or offer_map()
    local offer = picked and visit.offers[item_id(picked)]
    if offer then native.list_focus(list, offer) end
    write(list + L.scroll, advance.scroll)
    native.layout(list)
end

---------------------------------------------------------------------------------------
-- Clear Stratagems (a Mod Bindings Menu key)

local clear_key = {registered = false, down = false}

local function clear_pressed()
    local menu = rawget(_G, 'ModBindingsMenu')
    if not (type(menu) == 'table' and menu.api == 1) then return false end
    if not clear_key.registered then
        clear_key.registered = true
        local ok, res, why = pcall(menu.register_binding, CLEAR_BINDING, host_text(menu, 3, 'binding.clear', 64), nil,
                                   {category = host_text(menu, 3, 'option.mod', 64)})
        note('Mod Bindings Menu binding: ' .. ((ok and res) and 'registered' or ('not registered (' .. tostring(ok and why or res) .. ')')))
    end
    local ok, down = pcall(menu.is_down, CLEAR_BINDING)
    down = ok and down and true or false
    local edge = down and not clear_key.down
    clear_key.down = down
    return edge
end

-- Empties the four slots (each widget set to type 0), then writes the loadout block from the slots and saves it, as
-- a pick does. Not while readying or ready (the ready timer not idle).
local function clear_loadout(screen, index, list_open)
    if EXTRA.ready and u32(read(screen + L.panels + L.ready_timer, 4)) ~= L.timer_idle then
        note('Clear Stratagems: not while ready')
        return
    end
    local widgets = {}
    for k = 0, 3 do
        local widget = screen + WIDGET.base + k * L.slot_stride
        local t = u32(read(widget + WIDGET.type, 4))
        if t and t ~= 0 then widgets[#widgets + 1] = widget end
    end
    if #widgets == 0 then return end
    if list_open then native.close(screen) end
    for _, widget in ipairs(widgets) do native.set_widget(widget, 0) end
    native.slots_changed(screen + L.panels, -1)
    native.save(screen + L.block_base + index * L.block_stride)
    note(string.format('Clear Stratagems: %d slot(s) emptied', #widgets))
end

---------------------------------------------------------------------------------------
-- Frame step

local state = {ready = false, screen = nil}

local function leave_screen()
    restore_vehicles()
    state.screen = nil
    visit.offers, visit.block, visit.refused = nil, nil, nil
    ready.flash, advance.slot = nil, nil
end

local function loadout_screen()
    if not read_into(buffers.global, native.base + L.stack, 8) then return nil end
    local stack = buf_pointer(buffers.global, 0)
    if not stack or not read_into(buffers.stack, stack, L.slot + 8) then return nil end
    if buf_u32(buffers.stack, 0) ~= LOADOUT_SCREEN then return nil end
    return buf_pointer(buffers.stack, L.slot)
end

local function step()
    local clear = EXTRA.clear and clear_pressed()
    if not state.screen and M.frames % IDLE_POLL ~= 0 then return end
    local screen = loadout_screen()
    if screen ~= state.screen then
        if state.screen then leave_screen() end
        state.screen = screen
    end
    if not screen or not read_into(buffers.head, screen + SCREEN.head, SCREEN.head_size) then return end
    local index = buf_u32(buffers.head, SCREEN.local_index)
    local category = buf_u32(buffers.head, SCREEN.category)
    if index <= 3 and (EXTRA.ready or EXTRA.advance or EXTRA.clear) and read_into(buffers.byte, screen + L.list_open, 1) then
        local list_open = buffers.byte[0] ~= 0
        if EXTRA.ready then service_ready(screen, list_open) end
        if EXTRA.advance then service_advance(screen, index, list_open, category) end
        if clear then clear_loadout(screen, index, list_open) end
    end
    if category ~= STRATAGEMS or index > 3 then restore_vehicles(); return end
    service_list(screen, index)
end

local where_found = ''

local function report()
    local details = {'Copies per stratagem: ' .. settings.max_copies
                     .. (settings.menu and ' (Mod Options Menu)' or ' (default; Mod Options Menu not found)'),
                     'Game code found ' .. where_found,
                     'Ready with empty slots: ' .. (EXTRA.ready and 'on' or ('NOT AVAILABLE (' .. tostring(EXTRA.ready_why) .. ')')),
                     'List kept open after a replacement: '
                     .. (EXTRA.advance and 'on' or ('NOT AVAILABLE (' .. tostring(EXTRA.advance_why) .. ')')),
                     'List scroll kept: ' .. (EXTRA.scroll and 'on' or ('NOT AVAILABLE (' .. tostring(EXTRA.scroll_why) .. ')')),
                     'Clear Stratagems key: '
                     .. (EXTRA.clear and 'on' or ('NOT AVAILABLE (' .. tostring(EXTRA.clear_why) .. ')'))}
    write_status('OK - up to ' .. settings.max_copies .. ' of each stratagem can be picked in the Hellpod loadout',
                 details)
end

local function unavailable(reason)
    write_status('NOT AVAILABLE - this game version is not supported (' .. reason .. '); the loadout works as normal')
    note('Not available: ' .. reason)
    M.retired = true
end

-- With the code located: the layout, the native functions, then ready.
local function finish_start()
    local good, reason = read_layout()
    if good then
        for name, sig in pairs({mark = 'marker', select = 'select'}) do
            local ctype = name == 'mark' and 'void (*)(uint64_t, uint32_t, uint8_t)'  -- (list, offer, selectable)
                          or 'uint8_t (*)(uint64_t, uint32_t)'                         -- (list, offer or 0)
            local cast_ok, fn = pcall(ffi.cast, ctype, code:address(sig))
            if not cast_ok then good, reason = false, 'native function ' .. name .. ' unavailable' end
            native[name] = fn
        end
    end
    if not good then return unavailable(reason) end
    read_extras()
    if not EXTRA.ready then note('Ready with empty slots not available: ' .. tostring(EXTRA.ready_why)) end
    if not EXTRA.advance then note('List kept open not available: ' .. tostring(EXTRA.advance_why)) end
    for _, k in ipairs({'scroll', 'clear'}) do
        if not EXTRA[k] then note(k .. ' not available: ' .. tostring(EXTRA[k .. '_why'])) end
    end
    make_buffers()
    where_found = #code.moved == 0 and "at this game version's addresses"
                  or ('by search (' .. #code.moved .. ' moved: ' .. table.concat(code.moved, ', ') .. ')')
    note('Game code found ' .. where_found)
    state.ready = true
    -- The game's Text Language, for this mod's texts and every other mod's (bingus_text's shared registry).
    local tag, game_code = T.observe(read, native.base)
    note('Text language: ' .. tostring(T.language()) .. ' (game setting ' .. tostring(game_code or 'unreadable')
         .. ', tag ' .. tostring(tag) .. ')')
    report()
end

local function start()
    local ok, why = init_native()
    if not ok then
        write_status('NOT AVAILABLE - ' .. why .. '; the loadout works as normal')
        M.retired = true
        return
    end
    code = sigscan.new(SIGS, read, native.base)
    local all, reason = code:start()
    if all == nil then return unavailable(reason) end
    if all then return finish_start() end
    note('Searching game.dll for moved code')
end

local function frame()
    M.frames = M.frames + 1
    if not settings.menu then connect_menu() end
    if M.frames == 1 then
        start()
    elseif code and code.scan then
        if code:step() then finish_start() end
    elseif state.ready then
        if settings.dirty then settings.dirty = false; report() end
        step()
    end
end

local original_update = rawget(_G, 'update')
update = function(dt, ...)
    if not M.retired then
        local ok, err = xpcall(frame, debug.traceback)
        if not ok then
            M.errors = M.errors + 1
            note('Error: ' .. tostring(err))
            pcall(restore_vehicles)
            if M.errors >= 5 then
                M.retired = true
                write_status('STOPPED - repeated errors; the loadout works as normal (see FlexibleStratagems.log)')
            end
        end
    end
    if type(original_update) == 'function' then return original_update(dt, ...) end
end

note('Flexible Stratagems ' .. M.version .. ' loaded')
M._test = {state = state, visit = visit, code = function() return code end, layout = L, settings = settings,
           extra = EXTRA}
return M
