-- HD2-Addon: mods/alomare/flexible_stratagems
-- Flexible Stratagems by Alomare (formerly Stratagems Unleashed).
--
-- Lets the Hellpod loadout take the same stratagem more than once, vehicles included, under a ruleset chosen in Mod
-- Options Menu (escape menu > MODS; without it: Less Restricted):
--   Off              the game's own rules; the mod reads nothing but the screen check and writes nothing.
--   Less Restricted  up to two of each stratagem; when one is used (its cooldown starts), its copy gets a 10 second
--                    cooldown unless it already has a longer one. Eagles share their rearm already, and stratagems
--                    with a shared cooldown copy theirs already: those are left alone.
--   Unleashed        any stratagem any number of times, no extra cooldown.
-- Two rules are lifted in the stratagem list, on this game only (the loadout then goes out through the game's own
-- sync, so teammates need nothing):
--   * a stratagem already in the loadout is kept selectable: the list's refresh marks the loadout's stratagems as
--     equipped, and a press on an equipped item is refused; the mod marks them back through the game's own marker,
--     so picking one again runs the game's normal equip (slot, sync, save). Less Restricted marks back only those in
--     the loadout once. After such a pick the list's selection is cleared the game's way, since a press on the
--     selected item plays no pick sound;
--   * one mech, one FRV and one tank: the equip handler moves a second one of a kind into the slot holding the first.
--     Its kind bits (stratagem info flags: 0x100000 mech, 0x200000 FRV, 0x400000 tank) are cleared while the list is
--     open and put back when it closes (or the screen closes, the ruleset changes, or on any error).
-- Game updates: every address and structure offset the mod uses is read from the game's own code, found by code
-- signatures (at this build's addresses first, else by a search of game.dll spread over a few frames). Anything not
-- found, found twice or inconsistent turns the mod off (or, for the cooldown signatures, only the copy cooldown), and
-- the loadout works as normal. The verdict is the first line of
-- %LOCALAPPDATA%\CowboyBingus\Helldivers2\Logs\FlexibleStratagems_STATUS.log.
if rawget(_G, 'FlexibleStratagems') then return end

local ffi = require('ffi')
local bit = require('bit')

local M = {version = '3', frames = 0, errors = 0}
rawset(_G, 'FlexibleStratagems', M)

local loader = rawget(_G, 'CowboyBingusModLoader')

---------------------------------------------------------------------------------------
-- The game's code (research notes: NOTES.md beside this script)

-- BEGIN SIGNATURES (generated by research/signatures.py; game.dll build 25480438 addresses)
local SIGS = {
    {name = 'screen', rva = 0x1082ef0, text = '48 8B 05 ?? ?? ?? ?? 48 8B 88 ?? ?? ?? ?? 83 B9 ?? ?? ?? ?? FF 0F 95 C0 C3',
     fields = {stack = {'rip', {3}, {7}}, slot = {'u32', {10}}, local_index = {'u32', {16}}}},
    {name = 'category', rva = 0x146e0bc, text = '48 81 C1 ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 9F ?? ?? ?? ??',
     fields = {category = {'u32', {14}}}},
    {name = 'refresh_call', rva = 0x146e677, text = '8B 87 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? 48 69 D0 ?? ?? ?? ?? 48 83 C2 ?? 48 03 D7 E8 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {local_index = {'u32', {2}}, list = {'u32', {9}}, block_stride = {'u32', {16}}, block_base = {'u8', {23}}, refresh = {'call', {28}, {32}}}},
    {name = 'refresh_a', rva = 0x18d194f, text = '41 39 8C 24 ?? ?? ?? ?? 76 ?? 0F 1F 80 00 00 00 00 8B C1 FF C1 42 C6 84 20 ?? ?? ?? ?? 01 41 3B 8C 24 ?? ?? ?? ?? 72 ?? 45 39 BD ?? ?? ?? ?? 0F 86 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 8D 3D ?? ?? ?? ?? 0F 1F 40 00 66 66 0F 1F 84 00 00 00 00 00 4B 8D 0C 7F 48 03 C9 41 8B 84 CD ?? ?? ?? ?? 85 C0 75 ?? 48 8B C3 EB ?? 48 8B 04 C7 44 8B 58 04 45 85 DB 74 ??',
     fields = {list_count = {'u32', {4, 34}}, selectable = {'u32', {25}}, block_count = {'u32', {43}}, strat_table = {'rip', {63}, {67}}, block_entries = {'u32', {92}}}},
    {name = 'refresh_b', rva = 0x18d19c5, text = '4C 8B 0D ?? ?? ?? ?? 41 8B 91 ?? ?? ?? ?? 45 8B 91 ?? ?? ?? ?? 41 3B D2 73 ?? 4D 8D 81 ?? ?? ?? ?? 4D 8D 04 90 66 0F 1F 44 00 00 41 8B 00 48 8D 0C 40 49 8D 81 ?? ?? ?? ?? 44 39 5C C8 08 48 8D 04 C8 74 ?? FF C2 49 83 C0 04 41 3B D2 72 ?? EB ?? 48 85 C0 74 ?? 8B 50 04 45 33 C0 49 8B CC E8 ?? ?? ?? ??',
     fields = {offers = {'rip', {3}, {7}}, first = {'u32', {10}}, last = {'u32', {17}}, indices = {'u32', {29}}, entries = {'u32', {53}}, mark = {'call', {96}, {100}}}},
    {name = 'offers_count', rva = 0x146e1cf, text = '4C 8B 1D ?? ?? ?? ?? 85 D2 74 ?? 45 8B 83 ?? ?? ?? ?? 8B CE 45 85 C0 74 ?? 49 8D 83 ?? ?? ?? ??',
     fields = {offers = {'rip', {3}, {7}}, offers_count = {'u32', {14}}, entries = {'u32', {28}}}},
    {name = 'marker', rva = 0x18d1440, text = '48 89 74 24 10 57 48 83 EC 20 8B B9 14 1F 09 00 45 33 C9 45 33 DB 41 0F B6 F0 4C 8B D1 85 FF 0F 84 ?? ?? ?? ?? 48 89 5C 24 30 48 8D 99 18 23 09 00 44 8B 03 33 C0 45 85 C0 74 ?? 0F 1F 44 00 00 42 39 94 89 ?? ?? ?? ??',
     fields = {ids = {'u32', {68}}}},
    {name = 'select', rva = 0x18d10d0, text = '48 89 4C 24 08 56 41 55 41 56 48 83 EC 30 33 F6 48 89 5C 24 58 45 32 ED 4C 89 64 24 28 8B DA 4C 8B F1 44 8B E6 89 91 ?? ?? ?? ??',
     fields = {selected = {'u32', {39}}}},
    {name = 'kind_frv', rva = 0x146e2e0, text = '49 8B 0A 39 41 04 74 ?? 41 FF C0 49 83 C2 08 41 81 F8 ?? ?? ?? ?? 72 ?? 44 8B C6 48 8B C3 4C 8B DE EB ?? 44 8B C1 45 8B D8 4B 8B 04 DE F7 80 ?? ?? ?? ?? 00 00 20 00',
     fields = {types = {'u32', {18}}, flags = {'u32', {47}}}},
    {name = 'kind_mech', rva = 0x146e404, text = '45 85 C0 75 ?? 48 8B C3 EB ?? 41 8B C0 49 8B 04 C6 F7 80 ?? ?? ?? ?? 00 00 10 00',
     fields = {flags = {'u32', {19}}}},
    {name = 'kind_tank', rva = 0x146e4f5, text = '48 8B C3 45 85 C0 74 ?? 4B 8B 04 DE F7 80 ?? ?? ?? ?? 00 00 40 00',
     fields = {flags = {'u32', {14}}}},
    {name = 'cooldown_copy', rva = 0xb9a983, optional = true, text = '41 83 BF ?? ?? ?? ?? 00 0F 84 ?? ?? ?? ?? 45 33 C9 44 39 8B ?? ?? ?? ?? 0F 86 ?? ?? ?? ?? 41 8B C1 45 33 C0 48 69 D0 ?? ?? ?? ?? 48 03 15 ?? ?? ?? ?? 44 39 82 ?? ?? ?? ?? 76 ?? 66 90 8B 84 1F ?? ?? ?? ?? 4B 8D 0C 40 48 03 C9 39 84 CA ?? ?? ?? ?? 75 ?? 48 8B 84 1F ?? ?? ?? ?? 48 89 84 CA ?? ?? ?? ?? 48 8B 84 1F ?? ?? ?? ?? 48 89 84 CA ?? ?? ?? ?? 48 8B 84 1F ?? ?? ?? ?? 48 89 84 CA ?? ?? ?? ?? 41 FF C0 44 3B 82 ?? ?? ?? ?? 72 ??',
     fields = {shared = {'u32', {3}}, players = {'u32', {20}}, player_stride = {'u32', {39}}, synced = {'rip', {46}, {50}}, entry_count = {'u32', {53, 138}}, entry_type = {'u32', {64, 78}}, cd_end = {'u32', {88, 96}}, cd_start = {'u32', {104, 112}}, cd_base = {'u32', {120, 128}}}},
    {name = 'cooldown_start', rva = 0xb9a7cc, optional = true, text = '41 8B C0 48 8D 3C 40 48 C1 E7 04 49 03 FE 8B 94 1F ?? ?? ?? ?? 85 D2 74 ?? 4D 8B 3C D2 45 84 C9 74 ?? 48 8B 05 ?? ?? ?? ?? 48 8B 48 ?? 48 89 8C 1F ?? ?? ?? ??',
     fields = {entry_type = {'u32', {17}}, clock = {'rip', {37}, {41}}, clock_now = {'u8', {44}}, cd_start = {'u32', {49}}}},
    {name = 'eagle_family', rva = 0xb9a8af, optional = true, text = '83 FA ?? 74 ?? 41 83 BF ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ??',
     fields = {additional = {'u32', {8}}, eagle_rearm = {'u8', {2, 12}}}},
    {name = 'self_peer', rva = 0x5bae80, optional = true, text = '44 8B 4A 50 45 85 C9 74 ?? 48 8B 05 ?? ?? ?? ?? 33 C9 48 8B 90 ?? ?? ?? ??',
     fields = {session = {'rip', {12}, {16}}, peer = {'u32', {21}}}},
}
-- END SIGNATURES

-- BEGIN SIGNATURE ENGINE (tools/sigscan.lua, written by research/signatures.py: edit it there)
-- Signature engine v1: finds game.dll code by signatures and reads values from the matched code.
-- Canonical copy: tools/sigscan.lua in the workspace. Each mod's research/signatures.py writes this block and the
-- mod's SIGS table into its script (tools/sigspec.py), so every mod carries the same engine.
--
-- A signature is {name, rva, text, fields, optional}: text is hex bytes with '??' wildcards; rva is where the
-- generating build had it. fields = {field = {kind, {offset...}, {next...}}}: kind 'u8' / 'u32' (a value inside the
-- matched code), 'rip' (a global: the target of a rip-relative operand) or 'call' (a function: the target of a rel32
-- call); offset = each occurrence's byte position in the pattern, next = the end of its instruction. Every occurrence
-- must agree, and a field shared by several signatures must agree across them.
--
--   local code = sigscan.new(SIGS, read, base, validate)  -- read(address, size) -> string or nil; base = game.dll
--                                                        -- base; validate (optional) = {name = function(rva) -> bool}:
--                                                        -- extra checks a match must pass (decoys don't count)
--   code:start()                                 -- tries each signature at its rva; true when all were there
--   code:step()                                  -- else: one chunk of the search per call; true when finished
--   code.found[name] (rva), code.missing[name] (reason), code.values[field], code.problems (list)
local sigscan = {}
do
    local CHUNK, OVERLAP = 0x400000, 256

    local function u16(b, o) return b:byte(o + 1) + 256 * b:byte(o + 2) end
    local function u32(b, o)
        local x1, x2, x3, x4 = b:byte(o + 1, o + 4)
        return x1 + 256 * x2 + 65536 * x3 + 16777216 * x4
    end
    local function i32(b, o)
        local v = u32(b, o)
        return v >= 2147483648 and v - 4294967296 or v
    end

    local function parse(sig)
        local bytes = {}
        for part in sig.text:gmatch('%S+') do bytes[#bytes + 1] = part ~= '??' and tonumber(part, 16) or false end
        local best_at, best_len, at, len = 1, 0, nil, 0  -- the longest run of fixed bytes is searched for
        for i = 1, #bytes + 1 do
            if bytes[i] then
                if not at then at, len = i, 0 end
                len = len + 1
                if len > best_len then best_at, best_len = at, len end
            else
                at = nil
            end
        end
        local anchor = {}
        for i = best_at, best_at + best_len - 1 do anchor[#anchor + 1] = string.char(bytes[i]) end
        sig.bytes, sig.anchor, sig.anchor_at = bytes, table.concat(anchor), best_at - 1
    end

    local function matches(blob, pos, sig)  -- pos: 1-based start in blob
        local bytes = sig.bytes
        if pos < 1 or pos + #bytes - 1 > #blob then return false end
        for i = 1, #bytes do
            local b = bytes[i]
            if b and blob:byte(pos + i - 1) ~= b then return false end
        end
        return true
    end

    local Scanner = {}
    Scanner.__index = Scanner

    function sigscan.new(sigs, read, base, validate)
        return setmetatable({sigs = sigs, read = read, base = base, validate = validate or {}, found = {}, missing = {},
                             moved = {}, values = {}, problems = {}, scan = nil, done = false}, Scanner)
    end

    function Scanner:valid(name, rva)
        local check = self.validate[name]
        if not check then return true end
        local ok, good = pcall(check, rva)
        return ok and good and true or false
    end

    -- game.dll's sections: {rva, size, exec}.
    function Scanner:load_sections()
        local read, base = self.read, self.base
        local dos = read(base, 0x40)
        local pe = dos and dos:sub(1, 2) == 'MZ' and u32(dos, 0x3c)
        local nt = pe and pe < 0x10000 and read(base + pe, 0x18)
        if not nt or nt:sub(1, 4) ~= 'PE\0\0' then return nil end
        local count, opt = u16(nt, 6), u16(nt, 20)
        local headers = count <= 96 and read(base + pe + 24 + opt, count * 40)
        if not headers then return nil end
        local sections = {}
        for i = 0, count - 1 do
            local size, rva, flags = u32(headers, i * 40 + 8), u32(headers, i * 40 + 12), u32(headers, i * 40 + 36)
            if size > 0 then
                sections[#sections + 1] = {rva = rva, size = size, exec = math.floor(flags / 0x20000000) % 2 == 1}
            end
        end
        return sections
    end

    function Scanner:in_section(rva, exec)
        for _, s in ipairs(self.sections) do
            if s.exec == exec and rva >= s.rva and rva + 8 <= s.rva + s.size then return true end
        end
        return false
    end

    -- Tries every signature at its rva and starts a search for the others. True when all were there (done), false
    -- when a search started, nil and a reason when game.dll is unreadable.
    function Scanner:start()
        self.sections = self:load_sections()
        if not self.sections then return nil, 'game.dll headers unreadable' end
        local wanted = {}
        for _, sig in ipairs(self.sigs) do
            parse(sig)
            local blob = self.read(self.base + sig.rva, #sig.bytes)
            if blob and matches(blob, 1, sig) and self:valid(sig.name, sig.rva) then
                self.found[sig.name] = sig.rva
            else
                wanted[#wanted + 1] = sig
            end
        end
        if #wanted == 0 then
            self:resolve()
            return true
        end
        local exec = {}
        for _, s in ipairs(self.sections) do if s.exec then exec[#exec + 1] = s end end
        self.scan = {sections = exec, section = 1, offset = 0, wanted = wanted, hits = {}}
        for _, sig in ipairs(wanted) do self.scan.hits[sig.name] = {} end
        return false
    end

    -- One chunk of the search (every match is collected: a signature must match exactly once). True when finished.
    function Scanner:step()
        local scan = self.scan
        if not scan then return true end
        local s = scan.sections[scan.section]
        if s then
            local from = scan.offset
            local size = math.min(CHUNK + OVERLAP, s.size - from)
            local pieces = {}
            local blob = self.read(self.base + s.rva + from, size)
            if blob then
                pieces[1] = {from, blob}
            else
                for off = from, from + size - 1, 0x10000 do  -- skip unreadable pages
                    local piece = self.read(self.base + s.rva + off, math.min(0x10000 + OVERLAP, s.size - off))
                    if piece then pieces[#pieces + 1] = {off, piece} end
                end
            end
            for _, piece in ipairs(pieces) do
                local piece_from, data = piece[1], piece[2]
                for _, sig in ipairs(scan.wanted) do
                    local init = 1
                    while true do
                        local at = data:find(sig.anchor, init, true)
                        if not at then break end
                        local start = at - sig.anchor_at
                        local offset = piece_from + start - 1
                        -- Matches starting in the overlap belong to the next chunk.
                        if offset >= from and offset < from + CHUNK and matches(data, start, sig)
                           and self:valid(sig.name, s.rva + offset) then
                            local hits = scan.hits[sig.name]
                            hits[#hits + 1] = s.rva + offset
                        end
                        init = at + 1
                    end
                end
            end
            scan.offset = from + CHUNK
            if scan.offset >= s.size then scan.section, scan.offset = scan.section + 1, 0 end
            if scan.sections[scan.section] then return false end
        end
        for _, sig in ipairs(scan.wanted) do
            local hits = scan.hits[sig.name]
            if #hits == 1 then
                self.found[sig.name] = hits[1]
                self.moved[#self.moved + 1] = sig.name
            else
                self.missing[sig.name] = #hits == 0 and 'not found' or ('found ' .. #hits .. ' times')
            end
        end
        self.scan = nil
        self:resolve()
        return true
    end

    -- A field's value from the matched code; nil and a reason if its occurrences disagree or it points nowhere.
    function Scanner:field_value(sig, rva, spec)
        local blob = self.read(self.base + rva, #sig.bytes)
        if not blob then return nil, 'unreadable' end
        local value
        for k, off in ipairs(spec[2]) do
            local v
            if spec[1] == 'u8' then v = blob:byte(off + 1)
            elseif spec[1] == 'u32' then v = u32(blob, off)
            else v = rva + spec[3][k] + i32(blob, off) end
            if value and v ~= value then return nil, 'occurrences disagree' end
            value = v
        end
        if spec[1] == 'rip' and not self:in_section(value, false) then return nil, 'global not in a data section' end
        if spec[1] == 'call' and not self:in_section(value, true) then return nil, 'function not in a code section' end
        return value
    end

    -- Reads every field of the found signatures. A signature whose fields don't read becomes missing; a field that
    -- differs between signatures is dropped (nil) and listed in problems.
    function Scanner:resolve()
        local seen = {}
        for _, sig in ipairs(self.sigs) do
            local rva = self.found[sig.name]
            if rva then
                local got = {}
                for name, spec in pairs(sig.fields or {}) do
                    local v, why = self:field_value(sig, rva, spec)
                    if not v then
                        self.missing[sig.name] = string.format('field "%s" %s', name, why)
                        self.found[sig.name] = nil
                        got = nil
                        break
                    end
                    got[name] = v
                end
                for name, v in pairs(got or {}) do
                    if seen[name] ~= nil and seen[name] ~= v then
                        self.problems[#self.problems + 1] = string.format('"%s" differs between signatures', name)
                        seen[name] = false
                    elseif seen[name] == nil then
                        seen[name] = v
                    end
                end
            end
        end
        for name, v in pairs(seen) do self.values[name] = v or nil end
        self.done = true
    end

    -- The address of a found signature's match (plus an offset), or nil.
    function Scanner:address(name, offset)
        local rva = self.found[name]
        return rva and self.base + rva + (offset or 0)
    end

    -- Every missing signature as 'name (reason)', for logs and status files.
    function Scanner:missing_list()
        local out = {}
        for _, sig in ipairs(self.sigs) do
            if self.missing[sig.name] then out[#out + 1] = sig.name .. ' (' .. self.missing[sig.name] .. ')' end
        end
        return out
    end
end
-- END SIGNATURE ENGINE

-- Values the signatures don't carry: the loadout screen's type on the screen stack (+0), the stratagems category,
-- and bounds for the sanity checks.
local LOADOUT_SCREEN, STRATAGEMS = 11, 10
local BLOCK_MAX, ENTRY_SIZE, LIST_MAX = 32, 0x30, 256   -- entry size and offer entry layout are literal in refresh_a/b
local OFFER_STRIDE, OFFER_ID, OFFER_ITEM, INFO_ID = 0x18, 4, 8, 4
local VEHICLE_BITS = 0x700000                            -- literal in kind_mech / kind_frv / kind_tank
local IDLE_POLL = 10       -- frames between loadout screen checks while it is not open
local REQUIRED = {'screen', 'category', 'refresh_call', 'refresh_a', 'refresh_b', 'offers_count', 'marker', 'select',
                  'kind_frv', 'kind_mech', 'kind_tank'}
local COOLDOWN_SIGS = {'cooldown_copy', 'cooldown_start', 'eagle_family', 'self_peer'}

-- Rulesets: the Mod Options Menu choice's value is the index.
local RULESETS = {'off', 'less', 'unleashed'}
local RULESET_NAMES = {off = 'Off', less = 'Less Restricted', unleashed = 'Unleashed'}
local DEFAULT_RULESET = 2
local MAX_COPIES = {less = 2}           -- stratagems of one type a loadout may hold (none: unlimited)
local COPY_COOLDOWN = 10000000          -- Less Restricted: microseconds a copy waits after the other one is used
local COOLDOWN_POLL = 6                 -- frames between checks of the local player's cooldowns
local OPTION_ID = 'alomare.flexible_stratagems.ruleset'

---------------------------------------------------------------------------------------
-- Logging and status

local function open_log(name)
    if loader and type(loader.open_log) == 'function' then
        local ok, f = pcall(loader.open_log, name)
        if ok then return f end
    end
end

local log_file = open_log('FlexibleStratagems.log')
local log_lines = 0

local function note(msg)
    if not log_file or log_lines >= 1000 then return end
    log_lines = log_lines + 1
    pcall(function()
        log_file:write(string.format('[f%d] %s\n', M.frames, msg))
        log_file:flush()
    end)
end

local function write_status(verdict, details)
    local f = open_log('FlexibleStratagems_STATUS.log')
    if not f then return end
    pcall(function()
        f:write(verdict .. '\nFlexible Stratagems ' .. M.version .. '\n')
        for _, line in ipairs(details or {}) do f:write(line .. '\n') end
        f:close()
    end)
end

---------------------------------------------------------------------------------------
-- Texts (mod_text: src/bingus_text.lua and locales/, placed ahead of this script by the build)

local T = mod_text.module
local tr = T.new(mod_text.locales.en, mod_text.locales.bundled, function(message) note('Text: ' .. message) end)

---------------------------------------------------------------------------------------
-- Native memory. The per-frame reads go into fixed buffers; the rest (start, once per screen visit) allocate.

local native = {}

local function init_native()
    for _, decl in ipairs({
        'void *GetCurrentProcess(void);',
        'void *GetModuleHandleA(const char *name);',
        'int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);',
        'int WriteProcessMemory(void *process, void *address, const void *buffer, size_t size, size_t *written);',
    }) do pcall(ffi.cdef, decl) end
    local ok, k32 = pcall(ffi.load, 'kernel32')
    if not ok then return false, 'kernel32 unavailable' end
    native.k32, native.process = k32, k32.GetCurrentProcess()
    local game = k32.GetModuleHandleA('game.dll')
    if game == nil then return false, 'game.dll not loaded' end
    native.base = tonumber(ffi.cast('uint64_t', game))
    return true
end

local got = ffi.new('size_t[1]')

local function read_into(buf, address, size)
    return native.k32.ReadProcessMemory(native.process, ffi.cast('const void *', address), buf, size, got) ~= 0
           and tonumber(got[0]) == size
end

local function read(address, size)
    local buf = ffi.new('uint8_t[?]', size)
    if not read_into(buf, address, size) then return nil end
    return ffi.string(buf, size)
end

local function write(address, bytes)
    local ok = native.k32.WriteProcessMemory(native.process, ffi.cast('void *', address), bytes, #bytes, got)
    return ok ~= 0 and tonumber(got[0]) == #bytes
end

local function u32(blob, offset)
    offset = offset or 0
    if not blob or #blob < offset + 4 then return nil end
    local v = ffi.new('uint32_t[1]')
    ffi.copy(v, blob:sub(offset + 1, offset + 4), 4)
    return tonumber(v[0])
end

local function pointer_value(v)
    local a = tonumber(v)
    if a < 0x10000 or a >= 0x800000000000 then return nil end
    return a
end

local function pointer(blob)
    if not blob or #blob < 8 then return nil end
    local v = ffi.new('uint64_t[1]')
    ffi.copy(v, blob, 8)
    return pointer_value(v[0])
end

local function global(rva) return pointer(read(native.base + rva, 8)) end

local function u32_bytes(v) return ffi.string(ffi.new('uint32_t[1]', v), 4) end
local function u64_bytes(v) return ffi.string(ffi.new('uint64_t[1]', v), 8) end

-- Views into the fixed buffers.
local function buf_u32(buf, offset) return tonumber(ffi.cast('uint32_t *', buf + offset)[0]) end
local function buf_u64(buf, offset) return tonumber(ffi.cast('uint64_t *', buf + offset)[0]) end  -- exact below 2^53
local function buf_pointer(buf, offset) return pointer_value(ffi.cast('uint64_t *', buf + offset)[0]) end

---------------------------------------------------------------------------------------
-- The layout, from the matched code

local code = nil  -- the signature engine
local L = {}      -- field name -> value (offsets) or rva (globals, functions)
local SCREEN, LIST, BLOCK, SYNCED = {}, {}, {}, {}

-- Checks the pieces fit together (the engine already made every field agree across signatures).
local function read_layout()
    for _, name in ipairs(REQUIRED) do
        if not code.found[name] then return false, string.format('code "%s" %s', name, code.missing[name] or 'not found') end
    end
    if #code.problems > 0 then return false, code.problems[1] end
    for k, v in pairs(code.values) do L[k] = v end
    local found = code.found
    -- The functions: the refresh the handler calls holds refresh_a/b and calls the marker found on its own.
    if L.mark ~= found.marker then return false, 'the refresh does not call the marker' end
    for _, part in ipairs({'refresh_a', 'refresh_b'}) do
        if found[part] < L.refresh or found[part] > L.refresh + 0x1000 then return false, part .. ' outside the refresh' end
    end
    -- The spans read each frame: the screen head (local index .. category), the list (count .. selectable bytes),
    -- a loadout block (entries .. count).
    if L.category <= L.local_index or L.category - L.local_index > 0x1000 then return false, 'screen head layout' end
    SCREEN.head, SCREEN.head_size = L.local_index, L.category - L.local_index + 4
    SCREEN.local_index, SCREEN.category = 0, L.category - L.local_index
    SCREEN.blocks, SCREEN.block_size, SCREEN.list = L.block_base, L.block_stride, L.list
    LIST.span, LIST.count = L.list_count, 0
    LIST.selected, LIST.ids, LIST.selectable = L.selected - L.list_count, L.ids - L.list_count, L.selectable - L.list_count
    LIST.span_size = LIST.selectable + LIST_MAX
    for _, k in ipairs({'selected', 'ids', 'selectable'}) do
        if LIST[k] < 4 or LIST[k] > 0x1000 then return false, 'list layout (' .. k .. ')' end
    end
    if LIST.ids + LIST_MAX * 4 > LIST.selectable then return false, 'list layout (ids)' end
    BLOCK.entries, BLOCK.count = L.block_entries, L.block_count
    if BLOCK.count < BLOCK.entries + BLOCK_MAX * ENTRY_SIZE or BLOCK.count >= SCREEN.block_size then
        return false, 'loadout block layout'
    end
    if L.types < 2 or L.types > 0x1000 then return false, 'stratagem table size' end
    return true
end

-- The copy cooldown's layout (synced lists, clock, local peer), or nil and why it is unavailable.
local function read_cooldown_layout()
    for _, name in ipairs(COOLDOWN_SIGS) do
        if not code.found[name] then return nil, string.format('code "%s" %s', name, code.missing[name] or 'not found') end
    end
    for _, k in ipairs({'synced', 'players', 'player_stride', 'entry_count', 'entry_type', 'cd_start', 'cd_end',
                        'cd_base', 'clock', 'clock_now', 'session', 'peer', 'shared', 'additional', 'eagle_rearm'}) do
        if not L[k] then return nil, 'value "' .. k .. '" unavailable' end
    end
    -- Entry fields as offsets from the entry type; one span from the first entry to the count is read per check.
    local first = L.entry_type
    SYNCED.start, SYNCED.finish, SYNCED.base = L.cd_start - first, L.cd_end - first, L.cd_base - first
    SYNCED.count = L.entry_count - first
    if SYNCED.count < BLOCK_MAX * ENTRY_SIZE or SYNCED.count > 0x1000 or L.player_stride < L.entry_count + 4 then
        return nil, 'synced list layout'
    end
    for _, k in ipairs({'start', 'finish', 'base'}) do
        if SYNCED[k] < 8 or SYNCED[k] + 8 > ENTRY_SIZE then return nil, 'synced entry layout (' .. k .. ')' end
    end
    return true
end

---------------------------------------------------------------------------------------
-- Stratagem data

local function info_of(t)  -- the stratagem's info (its type at +0), from the game's stratagem table
    local info = t and t > 0 and t < L.types and global(L.strat_table + t * 8)
    if info and u32(read(info, 4)) == t then return info end
end

local function item_id(t)  -- the stratagem's item id (info +4)
    local info = info_of(t)
    return info and u32(read(info + INFO_ID, 4))
end

-- Stratagem item id -> offer id, from the offers table's stratagem range (built once per screen visit).
local function offer_map()
    local map = {}
    local offers = global(L.offers)
    local first = offers and u32(read(offers + L.first, 4))
    local last = offers and u32(read(offers + L.last, 4))
    local count = offers and u32(read(offers + L.offers_count, 4))
    if not first or not last or not count or last <= first or last - first > 512 or count > 0x10000 then return map end
    local indices = read(offers + L.indices + first * 4, (last - first) * 4)
    for k = 0, last - first - 1 do
        local index = u32(indices, k * 4)
        local entry = index and index < count and read(offers + L.entries + index * OFFER_STRIDE, OFFER_STRIDE)
        if entry then map[u32(entry, OFFER_ITEM)] = u32(entry, OFFER_ID) end
    end
    return map
end

---------------------------------------------------------------------------------------
-- Settings: the ruleset (Mod Options Menu, which may load before or after this addon)

local settings = {ruleset = RULESETS[DEFAULT_RULESET], menu = nil, dirty = false}  -- dirty: status to rewrite

-- Mod Options Menu v1.1 and later (version 2) take texts as functions and call them whenever the escape menu opens,
-- so they follow the game's language; v1.0 takes strings with byte limits, where a translation that does not fit
-- stays English.
local text_functions = {}
local function option_text(menu, key, bytes)
    if (tonumber(menu.version) or 1) >= 2 then
        local fn = text_functions[key]
        if not fn then fn = function() return tr(key) end; text_functions[key] = fn end
        return fn
    end
    local value = tr(key)
    return #value <= bytes and value or tr.english[key]
end

local ruleset_changed  -- defined with the list below

local function set_ruleset(value)
    local ruleset = RULESETS[value] or RULESETS[DEFAULT_RULESET]
    if ruleset == settings.ruleset then return end
    note('Ruleset: ' .. RULESET_NAMES[ruleset])
    settings.ruleset = ruleset
    ruleset_changed()
end

local function connect_menu()
    local menu = rawget(_G, 'ModOptionsMenu')
    if type(menu) ~= 'table' or menu.api ~= 1 then return false end
    settings.menu = menu
    -- OFF is shown in the game's own translation when passed as plain English.
    local ok, done, why = pcall(menu.register_option, OPTION_ID, {
        type = 'choice', mod = option_text(menu, 'option.mod', 40), label = option_text(menu, 'option.ruleset.label', 64),
        choices = {'Off', option_text(menu, 'option.ruleset.less', 48), option_text(menu, 'option.ruleset.unleashed', 48)},
        default = DEFAULT_RULESET, description = option_text(menu, 'option.ruleset.description', 400)})
    if ok and done then
        pcall(menu.on_change, OPTION_ID, function(value) set_ruleset(value) end)
        local read_ok, value = pcall(menu.get, OPTION_ID)
        set_ruleset(read_ok and value)
        note('Mod Options Menu connected (version ' .. tostring(menu.version or 1) .. ')')
    else
        note('Option not registered: ' .. tostring(ok and why or done))
    end
    return true
end

---------------------------------------------------------------------------------------
-- The vehicle rule: kind bits cleared while the list is open, restored after.

local vehicles = nil      -- {{info address, original flags, cleared flags}...}, found once
local vehicles_lifted = false

local function find_vehicles()
    local found = {}
    for t = 1, L.types - 1 do
        local info = global(L.strat_table + t * 8)
        local flags = info and u32(read(info, 4)) == t and u32(read(info + L.flags, 4))
        if flags and bit.band(flags, VEHICLE_BITS) ~= 0 then
            local cleared = bit.band(flags, bit.bnot(VEHICLE_BITS))
            if cleared < 0 then cleared = cleared + 4294967296 end
            found[#found + 1] = {info, flags, cleared}
        end
    end
    return found
end

local function lift_vehicles()
    if vehicles_lifted then return end
    vehicles_lifted = true
    vehicles = vehicles or find_vehicles()
    for _, v in ipairs(vehicles) do
        if u32(read(v[1] + L.flags, 4)) ~= v[2] then  -- the table moved or changed: look again
            vehicles = find_vehicles()
            break
        end
    end
    for _, v in ipairs(vehicles) do write(v[1] + L.flags, u32_bytes(v[3])) end
end

local function restore_vehicles()
    if not vehicles_lifted then return end
    vehicles_lifted = false
    for _, v in ipairs(vehicles or {}) do
        -- Only what still holds our value (never overwrite something the game changed meanwhile).
        if u32(read(v[1] + L.flags, 4)) == v[3] then write(v[1] + L.flags, u32_bytes(v[2])) end
    end
end

---------------------------------------------------------------------------------------
-- The stratagem list

local buffers = {}  -- sized from the layout once it is known
local visit = {offers = nil, block = nil, refused = nil}  -- per loadout screen visit

local function make_buffers()
    buffers.global = ffi.new('uint8_t[8]')
    buffers.stack = ffi.new('uint8_t[?]', L.slot + 8)
    buffers.head = ffi.new('uint8_t[?]', SCREEN.head_size)
    buffers.list = ffi.new('uint8_t[?]', LIST.span_size)
    buffers.block = ffi.new('uint8_t[?]', BLOCK.count - BLOCK.entries + 4)
    if SYNCED.count then buffers.synced = ffi.new('uint8_t[?]', SYNCED.count + 4) end
end

-- The loadout's stratagems as {offer id = copies}, plus the entries as a string (to notice picks).
local function loadout_offers(screen, index)
    local block = screen + SCREEN.blocks + index * SCREEN.block_size
    if not read_into(buffers.block, block + BLOCK.entries, BLOCK.count - BLOCK.entries + 4) then return nil end
    local count = buf_u32(buffers.block, BLOCK.count - BLOCK.entries)
    if count > BLOCK_MAX then return nil end
    visit.offers = visit.offers or offer_map()
    local copies = {}
    for e = 0, count - 1 do
        local offer = visit.offers[item_id(buf_u32(buffers.block, e * ENTRY_SIZE))]
        if offer then copies[offer] = (copies[offer] or 0) + 1 end
    end
    return copies, ffi.string(buffers.block, count * ENTRY_SIZE)
end

local function service_list(screen, index)
    local list = screen + SCREEN.list
    local list_buf = buffers.list
    if not read_into(list_buf, list + LIST.span, LIST.span_size) then return end
    local n = buf_u32(list_buf, LIST.count)
    if n == 0 or n > LIST_MAX then restore_vehicles(); return end
    lift_vehicles()
    -- Refused items: none in steady state (the loadout's are marked back); after a pick the refresh refuses the
    -- loadout's again. The same refused set as last time (other reasons, or the copy limit) is left alone without
    -- reading more.
    local refused = nil
    for i = 0, n - 1 do
        if list_buf[LIST.selectable + i] == 0 then
            refused = refused or {}
            refused[#refused + 1] = i
        end
    end
    if not refused then visit.refused = nil; return end
    local key = table.concat(refused, ',')
    if key == visit.refused then return end
    local copies, block = loadout_offers(screen, index)
    if not copies then return end
    if visit.block and block ~= visit.block then
        -- A pick: a selection left on a loadout stratagem would silence the next pick of it.
        local selected = buf_u32(list_buf, LIST.selected)
        if selected ~= 0 and copies[selected] then native.select(list, 0) end
    end
    visit.block = block
    local limit = MAX_COPIES[settings.ruleset]
    local kept = {}
    for _, i in ipairs(refused) do
        local offer = buf_u32(list_buf, LIST.ids + i * 4)
        if copies[offer] and (not limit or copies[offer] < limit) then
            native.mark(list, offer, 1)
        else
            kept[#kept + 1] = i
        end
    end
    visit.refused = #kept > 0 and table.concat(kept, ',') or nil
end

ruleset_changed = function()
    -- The list is recomputed under the new rules; Off gives the vehicle bits back at once.
    restore_vehicles()
    visit.refused = nil
    settings.dirty = true
end

---------------------------------------------------------------------------------------
-- Less Restricted's copy cooldown: when a stratagem's cooldown starts, its copies in the local player's synced list
-- (the live mission state) get a 10 second cooldown, written the way the game copies a shared cooldown (start, end,
-- base). The copy is kept on it for those 10 seconds in case a sync from the host resets it.

local cd = {available = false, player = nil, layout = nil, ends = {}, holds = {}, copyable = {}}

local function clock_now()
    local clock = global(L.clock)
    local v = clock and read(clock + L.clock_now, 8)
    if not v then return nil end
    local lo, hi = u32(v, 0), u32(v, 4)
    return hi * 4294967296 + lo
end

-- Whether a copy of type t should get the cooldown: not the Eagle family, not a shared-cooldown stratagem.
local function copyable(t)
    local known = cd.copyable[t]
    if known ~= nil then return known end
    local info = info_of(t)
    local additional = info and u32(read(info + L.additional, 4))
    local shared = info and u32(read(info + L.shared, 4))
    local ok = info ~= nil and t ~= L.eagle_rearm and additional ~= L.eagle_rearm and shared == 0
    cd.copyable[t] = ok
    note(string.format('Copy cooldown for stratagem %d: %s', t, ok and 'yes' or 'no (Eagle or shared cooldown)'))
    return ok
end

-- The local player's synced list address, or nil (cached; checked by its peer id each time).
local function local_list()
    local system = global(L.synced)
    local session = global(L.session)
    local peer = session and read(session + L.peer, 8)
    local players = system and u32(read(system + L.players, 4))
    if not peer or not players or players == 0 or players > 16 then return nil end
    if cd.player and cd.player < players and read(system + cd.player * L.player_stride, 8) == peer then
        return system + cd.player * L.player_stride
    end
    cd.player = nil
    for i = 0, players - 1 do
        if read(system + i * L.player_stride, 8) == peer then
            cd.player = i
            note('Local player: synced list ' .. i .. ' of ' .. players)
            return system + i * L.player_stride
        end
    end
end

local function hold_write(list, h)
    local entry = list + L.entry_type + h.index * ENTRY_SIZE
    write(entry + SYNCED.start, u64_bytes(h.start))
    write(entry + SYNCED.base, u64_bytes(h.start))
    write(entry + SYNCED.finish, u64_bytes(h.until_))
end

local function service_cooldowns()
    if settings.ruleset ~= 'less' or not cd.available then
        if next(cd.holds) or cd.layout then cd.holds, cd.ends, cd.layout = {}, {}, nil end
        return
    end
    if M.frames % COOLDOWN_POLL ~= 0 and not next(cd.holds) then return end
    local list = local_list()
    if not list or not read_into(buffers.synced, list + L.entry_type, SYNCED.count + 4) then
        cd.holds, cd.ends, cd.layout = {}, {}, nil
        return
    end
    local count = buf_u32(buffers.synced, SYNCED.count)
    if count > BLOCK_MAX then return end
    local now = clock_now()
    if not now then return end
    -- The list's types; a different list (a new mission, a loadout change) starts over: nothing to compare with.
    local types, by_type = {}, {}
    for e = 0, count - 1 do
        local t = buf_u32(buffers.synced, e * ENTRY_SIZE)
        types[#types + 1] = t
        if t ~= 0 then
            by_type[t] = by_type[t] or {}
            table.insert(by_type[t], e)
        end
    end
    local layout = list .. ':' .. table.concat(types, ',')
    if layout ~= cd.layout then
        cd.layout, cd.ends, cd.holds = layout, {}, {}
    end
    -- A cooldown that started since the last check (its end moved past now) puts the copies on hold.
    for e = 0, count - 1 do
        local finish = buf_u64(buffers.synced, e * ENTRY_SIZE + SYNCED.finish)
        local before = cd.ends[e]
        cd.ends[e] = finish
        local t = types[e + 1]
        if before and finish > before and finish > now and #by_type[t] > 1 and copyable(t) then
            for _, other in ipairs(by_type[t]) do
                if other ~= e then
                    cd.holds[other] = {index = other, type = t, start = now, until_ = now + COPY_COOLDOWN}
                    note(string.format('Stratagem %d used (entry %d): copy %d held for 10 s', t, e, other))
                end
            end
        end
    end
    -- Holds: a copy whose cooldown ends before the hold does gets the hold's (written again if a sync resets it).
    for index, h in pairs(cd.holds) do
        if now >= h.until_ or types[index + 1] ~= h.type then
            cd.holds[index] = nil
        elseif buf_u64(buffers.synced, index * ENTRY_SIZE + SYNCED.finish) < h.until_ then
            hold_write(list, h)
            cd.ends[index] = h.until_  -- our own write is not a new cooldown
        end
    end
end

---------------------------------------------------------------------------------------
-- Frame step

local state = {ready = false, screen = nil}

local function leave_screen()
    restore_vehicles()
    state.screen = nil
    visit.offers, visit.block, visit.refused = nil, nil, nil
end

local function loadout_screen()
    if not read_into(buffers.global, native.base + L.stack, 8) then return nil end
    local stack = buf_pointer(buffers.global, 0)
    if not stack or not read_into(buffers.stack, stack, L.slot + 8) then return nil end
    if buf_u32(buffers.stack, 0) ~= LOADOUT_SCREEN then return nil end
    return buf_pointer(buffers.stack, L.slot)
end

local function step()
    service_cooldowns()
    if settings.ruleset == 'off' then
        if state.screen then leave_screen() end
        return
    end
    if not state.screen and M.frames % IDLE_POLL ~= 0 then return end
    local screen = loadout_screen()
    if screen ~= state.screen then
        if state.screen then leave_screen() end
        state.screen = screen
    end
    if not screen or not read_into(buffers.head, screen + SCREEN.head, SCREEN.head_size) then return end
    local index = buf_u32(buffers.head, SCREEN.local_index)
    if buf_u32(buffers.head, SCREEN.category) ~= STRATAGEMS or index > 3 then restore_vehicles(); return end
    service_list(screen, index)
end

local where_found = ''

local function report()
    local details = {'Ruleset: ' .. RULESET_NAMES[settings.ruleset]
                     .. (settings.menu and ' (Mod Options Menu)' or ' (default; Mod Options Menu not found)'),
                     'Game code found ' .. where_found}
    if settings.ruleset == 'less' then
        details[#details + 1] = 'Copy cooldown: ' .. (cd.available and 'active' or ('NOT AVAILABLE (' .. cd.why .. ')'))
    end
    local verdict
    if settings.ruleset == 'off' then
        verdict = 'IDLE - ruleset Off: the loadout works as normal'
    elseif settings.ruleset == 'less' then
        verdict = 'OK - up to two of each stratagem can be picked in the Hellpod loadout'
    else
        verdict = 'OK - any stratagem can be picked any number of times in the Hellpod loadout'
    end
    write_status(verdict, details)
end

local function unavailable(reason)
    write_status('NOT AVAILABLE - this game version is not supported (' .. reason .. '); the loadout works as normal')
    note('Not available: ' .. reason)
    M.retired = true
end

-- With the code located: the layout, the native functions, then ready.
local function finish_start()
    local good, reason = read_layout()
    if good then
        for name, sig in pairs({mark = 'marker', select = 'select'}) do
            local ctype = name == 'mark' and 'void (*)(uint64_t, uint32_t, uint8_t)'  -- (list, offer, selectable)
                          or 'uint8_t (*)(uint64_t, uint32_t)'                         -- (list, offer or 0)
            local cast_ok, fn = pcall(ffi.cast, ctype, code:address(sig))
            if not cast_ok then good, reason = false, 'native function ' .. name .. ' unavailable' end
            native[name] = fn
        end
    end
    if not good then return unavailable(reason) end
    local cd_ok, cd_why = read_cooldown_layout()
    cd.available, cd.why = cd_ok and true or false, cd_why
    if not cd_ok then note('Copy cooldown not available: ' .. tostring(cd_why)) end
    make_buffers()
    where_found = #code.moved == 0 and "at this game version's addresses"
                  or ('by search (' .. #code.moved .. ' moved: ' .. table.concat(code.moved, ', ') .. ')')
    note('Game code found ' .. where_found)
    state.ready = true
    -- The game's Text Language, for this mod's texts and every other mod's (bingus_text's shared registry).
    local tag, game_code = T.observe(read, native.base)
    note('Text language: ' .. tostring(T.language()) .. ' (game setting ' .. tostring(game_code or 'unreadable')
         .. ', tag ' .. tostring(tag) .. ')')
    report()
end

local function start()
    local ok, why = init_native()
    if not ok then
        write_status('NOT AVAILABLE - ' .. why .. '; the loadout works as normal')
        M.retired = true
        return
    end
    code = sigscan.new(SIGS, read, native.base)
    local all, reason = code:start()
    if all == nil then return unavailable(reason) end
    if all then return finish_start() end
    note('Searching game.dll for moved code')
end

local function frame()
    M.frames = M.frames + 1
    if not settings.menu then connect_menu() end
    if M.frames == 1 then
        start()
    elseif code and code.scan then
        if code:step() then finish_start() end
    elseif state.ready then
        if settings.dirty then settings.dirty = false; report() end
        step()
    end
end

local original_update = rawget(_G, 'update')
update = function(dt, ...)
    if not M.retired then
        local ok, err = xpcall(frame, debug.traceback)
        if not ok then
            M.errors = M.errors + 1
            note('Error: ' .. tostring(err))
            pcall(restore_vehicles)
            if M.errors >= 5 then
                M.retired = true
                write_status('STOPPED - repeated errors; the loadout works as normal (see FlexibleStratagems.log)')
            end
        end
    end
    if type(original_update) == 'function' then return original_update(dt, ...) end
end

note('Flexible Stratagems ' .. M.version .. ' loaded')
M._test = {state = state, visit = visit, code = function() return code end, layout = L, settings = settings, cd = cd}
return M
