-- HD2-Addon: mods/alomare/stratagems_unleashed
-- Stratagems Unleashed by Alomare.
--
-- Lets the Hellpod loadout take the same stratagem more than once, vehicles included. Two rules are lifted in the
-- stratagem list, on this game only (the loadout then goes out through the game's own sync, so teammates need
-- nothing):
--   * a stratagem already in the loadout is kept selectable: the list's refresh marks the loadout's stratagems as
--     equipped, and a press on an equipped item is refused; the mod marks them back through the game's own marker,
--     so picking one again runs the game's normal equip (slot, sync, save). After such a pick the list's selection is
--     cleared the game's way, since a press on the selected item plays no pick sound;
--   * one mech, one FRV and one tank: the equip handler moves a second one of a kind into the slot holding the first.
--     Its kind bits (stratagem info flags: 0x100000 mech, 0x200000 FRV, 0x400000 tank) are cleared while the list is
--     open and put back when it closes (or the screen closes, or on any error).
-- Game updates: every address and structure offset the mod uses is read from the game's own code, found by code
-- signatures (at this build's addresses first, else by a search of game.dll spread over a few frames). Anything not
-- found, found twice or inconsistent turns the mod off, and the loadout works as normal. The verdict is the first
-- line of %LOCALAPPDATA%\CowboyBingus\Helldivers2\Logs\StratagemsUnleashed_STATUS.log.
if rawget(_G, 'StratagemsUnleashed') then return end

local ffi = require('ffi')

local M = {version = '2', frames = 0, errors = 0}
rawset(_G, 'StratagemsUnleashed', M)

local loader = rawget(_G, 'CowboyBingusModLoader')

---------------------------------------------------------------------------------------
-- The game's code (research notes: NOTES.md beside this script)

-- BEGIN SIGNATURES (generated by research/signatures.py; game.dll build 25480438 addresses)
local SIGS = {
    {name = 'screen', rva = 0x1082ef0, text = '48 8B 05 ?? ?? ?? ?? 48 8B 88 ?? ?? ?? ?? 83 B9 ?? ?? ?? ?? FF 0F 95 C0 C3',
     fields = {stack = {'rip', {3}, {7}}, slot = {'u32', {10}}, local_index = {'u32', {16}}}},
    {name = 'category', rva = 0x146e0bc, text = '48 81 C1 ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 9F ?? ?? ?? ??',
     fields = {category = {'u32', {14}}}},
    {name = 'refresh_call', rva = 0x146e677, text = '8B 87 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? 48 69 D0 ?? ?? ?? ?? 48 83 C2 ?? 48 03 D7 E8 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {local_index = {'u32', {2}}, list = {'u32', {9}}, block_stride = {'u32', {16}}, block_base = {'u8', {23}}, refresh = {'call', {28}, {32}}}},
    {name = 'refresh_a', rva = 0x18d194f, text = '41 39 8C 24 ?? ?? ?? ?? 76 ?? 0F 1F 80 00 00 00 00 8B C1 FF C1 42 C6 84 20 ?? ?? ?? ?? 01 41 3B 8C 24 ?? ?? ?? ?? 72 ?? 45 39 BD ?? ?? ?? ?? 0F 86 ?? ?? ?? ?? 48 8D 1D ?? ?? ?? ?? 48 8D 3D ?? ?? ?? ?? 0F 1F 40 00 66 66 0F 1F 84 00 00 00 00 00 4B 8D 0C 7F 48 03 C9 41 8B 84 CD ?? ?? ?? ?? 85 C0 75 ?? 48 8B C3 EB ?? 48 8B 04 C7 44 8B 58 04 45 85 DB 74 ??',
     fields = {list_count = {'u32', {4, 34}}, selectable = {'u32', {25}}, block_count = {'u32', {43}}, strat_table = {'rip', {63}, {67}}, block_entries = {'u32', {92}}}},
    {name = 'refresh_b', rva = 0x18d19c5, text = '4C 8B 0D ?? ?? ?? ?? 41 8B 91 ?? ?? ?? ?? 45 8B 91 ?? ?? ?? ?? 41 3B D2 73 ?? 4D 8D 81 ?? ?? ?? ?? 4D 8D 04 90 66 0F 1F 44 00 00 41 8B 00 48 8D 0C 40 49 8D 81 ?? ?? ?? ?? 44 39 5C C8 08 48 8D 04 C8 74 ?? FF C2 49 83 C0 04 41 3B D2 72 ?? EB ?? 48 85 C0 74 ?? 8B 50 04 45 33 C0 49 8B CC E8 ?? ?? ?? ??',
     fields = {offers = {'rip', {3}, {7}}, first = {'u32', {10}}, last = {'u32', {17}}, indices = {'u32', {29}}, entries = {'u32', {53}}, mark = {'call', {96}, {100}}}},
    {name = 'offers_count', rva = 0x146e1cf, text = '4C 8B 1D ?? ?? ?? ?? 85 D2 74 ?? 45 8B 83 ?? ?? ?? ?? 8B CE 45 85 C0 74 ?? 49 8D 83 ?? ?? ?? ??',
     fields = {offers = {'rip', {3}, {7}}, offers_count = {'u32', {14}}, entries = {'u32', {28}}}},
    {name = 'marker', rva = 0x18d1440, text = '48 89 74 24 10 57 48 83 EC 20 8B B9 14 1F 09 00 45 33 C9 45 33 DB 41 0F B6 F0 4C 8B D1 85 FF 0F 84 ?? ?? ?? ?? 48 89 5C 24 30 48 8D 99 18 23 09 00 44 8B 03 33 C0 45 85 C0 74 ?? 0F 1F 44 00 00 42 39 94 89 ?? ?? ?? ??',
     fields = {ids = {'u32', {68}}}},
    {name = 'select', rva = 0x18d10d0, text = '48 89 4C 24 08 56 41 55 41 56 48 83 EC 30 33 F6 48 89 5C 24 58 45 32 ED 4C 89 64 24 28 8B DA 4C 8B F1 44 8B E6 89 91 ?? ?? ?? ??',
     fields = {selected = {'u32', {39}}}},
    {name = 'kind_frv', rva = 0x146e2e0, text = '49 8B 0A 39 41 04 74 ?? 41 FF C0 49 83 C2 08 41 81 F8 ?? ?? ?? ?? 72 ?? 44 8B C6 48 8B C3 4C 8B DE EB ?? 44 8B C1 45 8B D8 4B 8B 04 DE F7 80 ?? ?? ?? ?? 00 00 20 00',
     fields = {types = {'u32', {18}}, flags = {'u32', {47}}}},
    {name = 'kind_mech', rva = 0x146e404, text = '45 85 C0 75 ?? 48 8B C3 EB ?? 41 8B C0 49 8B 04 C6 F7 80 ?? ?? ?? ?? 00 00 10 00',
     fields = {flags = {'u32', {19}}}},
    {name = 'kind_tank', rva = 0x146e4f5, text = '48 8B C3 45 85 C0 74 ?? 4B 8B 04 DE F7 80 ?? ?? ?? ?? 00 00 40 00',
     fields = {flags = {'u32', {14}}}},
}
-- END SIGNATURES

-- Values the signatures don't carry: the loadout screen's type on the screen stack (+0), the stratagems category,
-- and bounds for the sanity checks.
local LOADOUT_SCREEN, STRATAGEMS = 11, 10
local BLOCK_MAX, ENTRY_SIZE, LIST_MAX = 32, 0x30, 256   -- entry size and offer entry layout are literal in refresh_a/b
local OFFER_STRIDE, OFFER_ID, OFFER_ITEM, INFO_ID = 0x18, 4, 8, 4
local VEHICLE_BITS = 0x700000                            -- literal in kind_mech / kind_frv / kind_tank
local IDLE_POLL = 10       -- frames between loadout screen checks while it is not open
local SCAN_CHUNK = 0x400000  -- bytes of game.dll searched per frame when the code moved

---------------------------------------------------------------------------------------
-- Logging and status

local function open_log(name)
    if loader and type(loader.open_log) == 'function' then
        local ok, f = pcall(loader.open_log, name)
        if ok then return f end
    end
end

local log_file = open_log('StratagemsUnleashed.log')
local log_lines = 0

local function note(msg)
    if not log_file or log_lines >= 500 then return end
    log_lines = log_lines + 1
    pcall(function()
        log_file:write(string.format('[f%d] %s\n', M.frames, msg))
        log_file:flush()
    end)
end

local function write_status(verdict, detail)
    local f = open_log('StratagemsUnleashed_STATUS.log')
    if not f then return end
    pcall(function()
        f:write(verdict .. '\nStratagems Unleashed ' .. M.version .. '\n' .. (detail and detail .. '\n' or ''))
        f:close()
    end)
end

---------------------------------------------------------------------------------------
-- Native memory. The per-frame reads go into fixed buffers; the rest (start, once per screen visit) allocate.

local native = {}

local function init_native()
    for _, decl in ipairs({
        'void *GetCurrentProcess(void);',
        'void *GetModuleHandleA(const char *name);',
        'int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);',
        'int WriteProcessMemory(void *process, void *address, const void *buffer, size_t size, size_t *written);',
    }) do pcall(ffi.cdef, decl) end
    local ok, k32 = pcall(ffi.load, 'kernel32')
    if not ok then return false, 'kernel32 unavailable' end
    native.k32, native.process = k32, k32.GetCurrentProcess()
    local game = k32.GetModuleHandleA('game.dll')
    if game == nil then return false, 'game.dll not loaded' end
    native.base = tonumber(ffi.cast('uint64_t', game))
    return true
end

local got = ffi.new('size_t[1]')

local function read_into(buf, address, size)
    return native.k32.ReadProcessMemory(native.process, ffi.cast('const void *', address), buf, size, got) ~= 0
           and tonumber(got[0]) == size
end

local function read(address, size)
    local buf = ffi.new('uint8_t[?]', size)
    if not read_into(buf, address, size) then return nil end
    return ffi.string(buf, size)
end

local function write(address, bytes)
    local ok = native.k32.WriteProcessMemory(native.process, ffi.cast('void *', address), bytes, #bytes, got)
    return ok ~= 0 and tonumber(got[0]) == #bytes
end

local function u16(blob, offset)
    if not blob or #blob < offset + 2 then return nil end
    return blob:byte(offset + 1) + 256 * blob:byte(offset + 2)
end

local function u32(blob, offset)
    offset = offset or 0
    if not blob or #blob < offset + 4 then return nil end
    local v = ffi.new('uint32_t[1]')
    ffi.copy(v, blob:sub(offset + 1, offset + 4), 4)
    return tonumber(v[0])
end

local function i32(blob, offset)
    local v = u32(blob, offset)
    if v and v >= 2147483648 then v = v - 4294967296 end
    return v
end

local function pointer_value(v)
    local a = tonumber(v)
    if a < 0x10000 or a >= 0x800000000000 then return nil end
    return a
end

local function pointer(blob)
    if not blob or #blob < 8 then return nil end
    local v = ffi.new('uint64_t[1]')
    ffi.copy(v, blob, 8)
    return pointer_value(v[0])
end

local function global(rva) return pointer(read(native.base + rva, 8)) end

local function u32_bytes(v) return ffi.string(ffi.new('uint32_t[1]', v), 4) end

-- Views into the fixed buffers.
local function buf_u32(buf, offset) return tonumber(ffi.cast('uint32_t *', buf + offset)[0]) end
local function buf_pointer(buf, offset) return pointer_value(ffi.cast('uint64_t *', buf + offset)[0]) end

---------------------------------------------------------------------------------------
-- Finding the game's code. Each signature ('??' = any byte) is tried at this build's address; the ones not there
-- are searched for in game.dll's executable sections, SCAN_CHUNK bytes per frame, and must match exactly once.
-- Then each field is read from the matched code (every place it occurs must agree): a value, or the target of a
-- rip-relative operand or call.

local code = {sections = nil, found = {}, moved = {}, scan = nil}

local function parse_sig(sig)
    local bytes = {}
    for part in sig.text:gmatch('%S+') do bytes[#bytes + 1] = part ~= '??' and tonumber(part, 16) or false end
    local best_at, best_len, at, len = 1, 0, nil, 0  -- the longest run of fixed bytes is searched for
    for i = 1, #bytes + 1 do
        if bytes[i] then
            if not at then at, len = i, 0 end
            len = len + 1
            if len > best_len then best_at, best_len = at, len end
        else
            at = nil
        end
    end
    local anchor = {}
    for i = best_at, best_at + best_len - 1 do anchor[#anchor + 1] = string.char(bytes[i]) end
    sig.bytes, sig.anchor, sig.anchor_at = bytes, table.concat(anchor), best_at - 1
end

local function sig_matches(blob, pos, sig)  -- pos: 1-based start in blob
    local bytes = sig.bytes
    if pos < 1 or pos + #bytes - 1 > #blob then return false end
    for i = 1, #bytes do
        local b = bytes[i]
        if b and blob:byte(pos + i - 1) ~= b then return false end
    end
    return true
end

-- game.dll's sections: {rva, size, exec}.
local function pe_sections()
    local dos = read(native.base, 0x40)
    local pe = dos and dos:sub(1, 2) == 'MZ' and u32(dos, 0x3c)
    local nt = pe and pe < 0x10000 and read(native.base + pe, 0x18)
    if not nt or nt:sub(1, 4) ~= 'PE\0\0' then return nil end
    local count, opt = u16(nt, 6), u16(nt, 20)
    local headers = count and count <= 96 and read(native.base + pe + 24 + opt, count * 40)
    if not headers then return nil end
    local sections = {}
    for i = 0, count - 1 do
        local size, rva, flags = u32(headers, i * 40 + 8), u32(headers, i * 40 + 12), u32(headers, i * 40 + 36)
        if size > 0 then sections[#sections + 1] = {rva = rva, size = size, exec = flags >= 0x20000000
                                                     and math.floor(flags / 0x20000000) % 2 == 1} end
    end
    return sections
end

local function in_section(rva, exec)
    for _, s in ipairs(code.sections) do
        if s.exec == exec and rva >= s.rva and rva + 8 <= s.rva + s.size then return true end
    end
    return false
end

-- One step of the search: the next chunk of the executable sections. True when done.
local function scan_step()
    local scan = code.scan
    local s = scan.sections[scan.section]
    if not s then return true end
    local from = scan.offset
    local size = math.min(SCAN_CHUNK + 256, s.size - from)
    local pieces = {}
    local blob = read(native.base + s.rva + from, size)
    if blob then
        pieces[1] = {from, blob}
    else
        for off = from, from + size - 1, 0x10000 do  -- skip unreadable pages
            local piece = read(native.base + s.rva + off, math.min(0x10000 + 256, s.size - off))
            if piece then pieces[#pieces + 1] = {off, piece} end
        end
    end
    for _, piece in ipairs(pieces) do
        local piece_from, data = piece[1], piece[2]
        for _, sig in ipairs(scan.missing) do
            local init = 1
            while true do
                local at = data:find(sig.anchor, init, true)
                if not at then break end
                local start = at - sig.anchor_at
                local offset = piece_from + start - 1
                -- Matches starting in the overlap belong to the next chunk.
                if offset >= from and offset < from + SCAN_CHUNK and sig_matches(data, start, sig) then
                    local hits = scan.hits[sig.name]
                    hits[#hits + 1] = s.rva + offset
                end
                init = at + 1
            end
        end
    end
    scan.offset = from + SCAN_CHUNK
    if scan.offset >= s.size then scan.section, scan.offset = scan.section + 1, 0 end
    return scan.sections[scan.section] == nil
end

-- A field's value from the matched code; nil if its occurrences disagree.
local function field_value(sig, rva, spec)
    local blob = read(native.base + rva, #sig.bytes)
    local value
    for k, off in ipairs(spec[2]) do
        local v
        if spec[1] == 'u8' then v = blob and blob:byte(off + 1)
        elseif spec[1] == 'u32' then v = u32(blob, off)
        else v = blob and rva + spec[3][k] + i32(blob, off) end
        if not v or (value and v ~= value) then return nil end
        value = v
    end
    return value
end

-- Tries every signature at this build's address; starts a search for the others. True when all were there.
local function locate_code()
    code.sections = pe_sections()
    if not code.sections then return nil, 'game.dll headers unreadable' end
    local missing, exec = {}, {}
    for _, sig in ipairs(SIGS) do
        parse_sig(sig)
        local blob = read(native.base + sig.rva, #sig.bytes)
        if blob and sig_matches(blob, 1, sig) then code.found[sig.name] = sig.rva else missing[#missing + 1] = sig end
    end
    if #missing == 0 then return true end
    for _, s in ipairs(code.sections) do if s.exec then exec[#exec + 1] = s end end
    code.scan = {sections = exec, section = 1, offset = 0, missing = missing, hits = {}}
    for _, sig in ipairs(missing) do code.scan.hits[sig.name] = {} end
    return false
end

-- After the search: each missing signature needs exactly one match.
local function finish_scan()
    for _, sig in ipairs(code.scan.missing) do
        local hits = code.scan.hits[sig.name]
        if #hits ~= 1 then
            return false, string.format('code "%s" %s', sig.name, #hits == 0 and 'not found' or ('found ' .. #hits .. ' times'))
        end
        code.found[sig.name], code.moved[#code.moved + 1] = hits[1], sig.name
    end
    code.scan = nil
    return true
end

---------------------------------------------------------------------------------------
-- The layout, from the matched code

local L = {}      -- field name -> value (offsets) or rva (globals, functions)
local SCREEN, LIST, BLOCK = {}, {}, {}

-- Reads every field (a name used by several signatures must agree), then checks the pieces fit together.
local function read_layout()
    for _, sig in ipairs(SIGS) do
        local rva = code.found[sig.name]
        for name, spec in pairs(sig.fields) do
            local v = field_value(sig, rva, spec)
            if not v then return false, string.format('"%s" in code "%s" is inconsistent', name, sig.name) end
            if spec[1] == 'rip' and not in_section(v, false) then return false, 'global "' .. name .. '" not in data' end
            if spec[1] == 'call' and not in_section(v, true) then return false, 'function "' .. name .. '" not in code' end
            if L[name] and L[name] ~= v then return false, string.format('"%s" differs between signatures', name) end
            L[name] = v
        end
    end
    local found = code.found
    -- The functions: the refresh the handler calls holds refresh_a/b and calls the marker found on its own.
    if L.mark ~= found.marker then return false, 'the refresh does not call the marker' end
    for _, part in ipairs({'refresh_a', 'refresh_b'}) do
        if found[part] < L.refresh or found[part] > L.refresh + 0x1000 then return false, part .. ' outside the refresh' end
    end
    -- The spans read each frame: the screen head (local index .. category), the list (count .. selectable bytes),
    -- a loadout block (entries .. count).
    if L.category <= L.local_index or L.category - L.local_index > 0x1000 then return false, 'screen head layout' end
    SCREEN.head, SCREEN.head_size = L.local_index, L.category - L.local_index + 4
    SCREEN.local_index, SCREEN.category = 0, L.category - L.local_index
    SCREEN.blocks, SCREEN.block_size, SCREEN.list = L.block_base, L.block_stride, L.list
    LIST.span, LIST.count = L.list_count, 0
    LIST.selected, LIST.ids, LIST.selectable = L.selected - L.list_count, L.ids - L.list_count, L.selectable - L.list_count
    LIST.span_size = LIST.selectable + LIST_MAX
    for _, k in ipairs({'selected', 'ids', 'selectable'}) do
        if LIST[k] < 4 or LIST[k] > 0x1000 then return false, 'list layout (' .. k .. ')' end
    end
    if LIST.ids + LIST_MAX * 4 > LIST.selectable then return false, 'list layout (ids)' end
    BLOCK.entries, BLOCK.count = L.block_entries, L.block_count
    if BLOCK.count < BLOCK.entries + BLOCK_MAX * ENTRY_SIZE or BLOCK.count >= SCREEN.block_size then
        return false, 'loadout block layout'
    end
    if L.types < 2 or L.types > 0x1000 then return false, 'stratagem table size' end
    return true
end

---------------------------------------------------------------------------------------
-- Stratagem data

local function item_id(t)  -- the stratagem's item id (info +4), from the game's stratagem table
    local info = t and t > 0 and t < L.types and global(L.strat_table + t * 8)
    local head = info and read(info, 8)
    if head and u32(head, 0) == t then return u32(head, INFO_ID) end
end

-- Stratagem item id -> offer id, from the offers table's stratagem range (built once per screen visit).
local function offer_map()
    local map = {}
    local offers = global(L.offers)
    local first = offers and u32(read(offers + L.first, 4))
    local last = offers and u32(read(offers + L.last, 4))
    local count = offers and u32(read(offers + L.offers_count, 4))
    if not first or not last or not count or last <= first or last - first > 512 or count > 0x10000 then return map end
    local indices = read(offers + L.indices + first * 4, (last - first) * 4)
    for k = 0, last - first - 1 do
        local index = u32(indices, k * 4)
        local entry = index and index < count and read(offers + L.entries + index * OFFER_STRIDE, OFFER_STRIDE)
        if entry then map[u32(entry, OFFER_ITEM)] = u32(entry, OFFER_ID) end
    end
    return map
end

---------------------------------------------------------------------------------------
-- The vehicle rule: kind bits cleared while the list is open, restored after.

local vehicles = nil      -- {{info address, original flags, cleared flags}...}, found once
local vehicles_lifted = false

local function find_vehicles()
    local found = {}
    for t = 1, L.types - 1 do
        local info = global(L.strat_table + t * 8)
        local flags = info and u32(read(info, 4)) == t and u32(read(info + L.flags, 4))
        if flags and bit.band(flags, VEHICLE_BITS) ~= 0 then
            local cleared = bit.band(flags, bit.bnot(VEHICLE_BITS))
            if cleared < 0 then cleared = cleared + 4294967296 end
            found[#found + 1] = {info, flags, cleared}
        end
    end
    return found
end

local function lift_vehicles()
    if vehicles_lifted then return end
    vehicles_lifted = true
    vehicles = vehicles or find_vehicles()
    for _, v in ipairs(vehicles) do
        if u32(read(v[1] + L.flags, 4)) ~= v[2] then  -- the table moved or changed: look again
            vehicles = find_vehicles()
            break
        end
    end
    for _, v in ipairs(vehicles) do write(v[1] + L.flags, u32_bytes(v[3])) end
end

local function restore_vehicles()
    if not vehicles_lifted then return end
    vehicles_lifted = false
    for _, v in ipairs(vehicles or {}) do
        -- Only what still holds our value (never overwrite something the game changed meanwhile).
        if u32(read(v[1] + L.flags, 4)) == v[3] then write(v[1] + L.flags, u32_bytes(v[2])) end
    end
end

---------------------------------------------------------------------------------------
-- The stratagem list

local buffers = {}  -- sized from the layout once it is known
local visit = {offers = nil, block = nil, refused = nil}  -- per loadout screen visit

local function make_buffers()
    buffers.global = ffi.new('uint8_t[8]')
    buffers.stack = ffi.new('uint8_t[?]', L.slot + 8)
    buffers.head = ffi.new('uint8_t[?]', SCREEN.head_size)
    buffers.list = ffi.new('uint8_t[?]', LIST.span_size)
    buffers.block = ffi.new('uint8_t[?]', BLOCK.count - BLOCK.entries + 4)
end

-- The loadout's stratagems as {offer id = true}, plus the entries as a string (to notice picks).
local function loadout_offers(screen, index)
    local block = screen + SCREEN.blocks + index * SCREEN.block_size
    if not read_into(buffers.block, block + BLOCK.entries, BLOCK.count - BLOCK.entries + 4) then return nil end
    local count = buf_u32(buffers.block, BLOCK.count - BLOCK.entries)
    if count > BLOCK_MAX then return nil end
    visit.offers = visit.offers or offer_map()
    local wanted = {}
    for e = 0, count - 1 do
        local offer = visit.offers[item_id(buf_u32(buffers.block, e * ENTRY_SIZE))]
        if offer then wanted[offer] = true end
    end
    return wanted, ffi.string(buffers.block, count * ENTRY_SIZE)
end

local function service_list(screen, index)
    local list = screen + SCREEN.list
    local list_buf = buffers.list
    if not read_into(list_buf, list + LIST.span, LIST.span_size) then return end
    local n = buf_u32(list_buf, LIST.count)
    if n == 0 or n > LIST_MAX then restore_vehicles(); return end
    lift_vehicles()
    -- Refused items: none in steady state (the loadout's are marked back); after a pick the refresh refuses the
    -- loadout's again. The same refused set as last time (other reasons) is left alone without reading more.
    local refused = nil
    for i = 0, n - 1 do
        if list_buf[LIST.selectable + i] == 0 then
            refused = refused or {}
            refused[#refused + 1] = i
        end
    end
    if not refused then visit.refused = nil; return end
    local key = table.concat(refused, ',')
    if key == visit.refused then return end
    local wanted, block = loadout_offers(screen, index)
    if not wanted then return end
    if visit.block and block ~= visit.block then
        -- A pick: a selection left on a loadout stratagem would silence the next pick of it.
        local selected = buf_u32(list_buf, LIST.selected)
        if selected ~= 0 and wanted[selected] then native.select(list, 0) end
    end
    visit.block = block
    local kept = {}
    for _, i in ipairs(refused) do
        local offer = buf_u32(list_buf, LIST.ids + i * 4)
        if wanted[offer] then native.mark(list, offer, 1) else kept[#kept + 1] = i end
    end
    visit.refused = #kept > 0 and table.concat(kept, ',') or nil
end

---------------------------------------------------------------------------------------
-- Frame step

local state = {ready = false, screen = nil}

local function leave_screen()
    restore_vehicles()
    state.screen = nil
    visit.offers, visit.block, visit.refused = nil, nil, nil
end

local function loadout_screen()
    if not read_into(buffers.global, native.base + L.stack, 8) then return nil end
    local stack = buf_pointer(buffers.global, 0)
    if not stack or not read_into(buffers.stack, stack, L.slot + 8) then return nil end
    if buf_u32(buffers.stack, 0) ~= LOADOUT_SCREEN then return nil end
    return buf_pointer(buffers.stack, L.slot)
end

local function step()
    if not state.screen and M.frames % IDLE_POLL ~= 0 then return end
    local screen = loadout_screen()
    if screen ~= state.screen then
        if state.screen then leave_screen() end
        state.screen = screen
    end
    if not screen or not read_into(buffers.head, screen + SCREEN.head, SCREEN.head_size) then return end
    local index = buf_u32(buffers.head, SCREEN.local_index)
    if buf_u32(buffers.head, SCREEN.category) ~= STRATAGEMS or index > 3 then restore_vehicles(); return end
    service_list(screen, index)
end

local function unavailable(reason)
    write_status('NOT AVAILABLE - this game version is not supported (' .. reason .. '); the loadout works as normal')
    note('Not available: ' .. reason)
    M.retired = true
end

-- With the code located: the layout, the native functions, then ready.
local function finish_start()
    local good, reason = read_layout()
    if good then
        for name, sig in pairs({mark = 'marker', select = 'select'}) do
            local ctype = name == 'mark' and 'void (*)(uint64_t, uint32_t, uint8_t)'  -- (list, offer, selectable)
                          or 'uint8_t (*)(uint64_t, uint32_t)'                         -- (list, offer or 0)
            local cast_ok, fn = pcall(ffi.cast, ctype, native.base + code.found[sig])
            if not cast_ok then good, reason = false, 'native function ' .. name .. ' unavailable' end
            native[name] = fn
        end
    end
    if not good then return unavailable(reason) end
    make_buffers()
    local where = #code.moved == 0 and "at this game version's addresses"
                  or ('by search (' .. #code.moved .. ' moved: ' .. table.concat(code.moved, ', ') .. ')')
    write_status('OK - duplicate stratagems and vehicles can be picked in the Hellpod loadout', 'Game code found ' .. where)
    note('Game code found ' .. where)
    state.ready = true
end

local function start()
    local ok, why = init_native()
    if not ok then
        write_status('NOT AVAILABLE - ' .. why .. '; the loadout works as normal')
        M.retired = true
        return
    end
    local all, reason = locate_code()
    if all == nil then return unavailable(reason) end
    if all then return finish_start() end
    note('Searching game.dll for moved code: ' .. #code.scan.missing .. ' signature(s)')
end

local function frame()
    M.frames = M.frames + 1
    if M.frames == 1 then
        start()
    elseif code.scan then
        if scan_step() then
            local ok, reason = finish_scan()
            if ok then finish_start() else unavailable(reason) end
        end
    elseif state.ready then
        step()
    end
end

local original_update = rawget(_G, 'update')
update = function(dt, ...)
    if not M.retired then
        local ok, err = xpcall(frame, debug.traceback)
        if not ok then
            M.errors = M.errors + 1
            note('Error: ' .. tostring(err))
            pcall(restore_vehicles)
            if M.errors >= 5 then
                M.retired = true
                write_status('STOPPED - repeated errors; the loadout works as normal (see StratagemsUnleashed.log)')
            end
        end
    end
    if type(original_update) == 'function' then return original_update(dt, ...) end
end

note('Stratagems Unleashed ' .. M.version .. ' loaded')
M._test = {state = state, visit = visit, code = code, layout = L}  -- offline tests
return M
